// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/protobuf-spec/qpu.proto

package qpu

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SnapshotTime_SnapshotTimeType int32

const (
	SnapshotTime_LATEST      SnapshotTime_SnapshotTimeType = 0
	SnapshotTime_ZERO        SnapshotTime_SnapshotTimeType = 1
	SnapshotTime_INF         SnapshotTime_SnapshotTimeType = 2
	SnapshotTime_VECTORCLOCK SnapshotTime_SnapshotTimeType = 3
)

var SnapshotTime_SnapshotTimeType_name = map[int32]string{
	0: "LATEST",
	1: "ZERO",
	2: "INF",
	3: "VECTORCLOCK",
}

var SnapshotTime_SnapshotTimeType_value = map[string]int32{
	"LATEST":      0,
	"ZERO":        1,
	"INF":         2,
	"VECTORCLOCK": 3,
}

func (x SnapshotTime_SnapshotTimeType) String() string {
	return proto.EnumName(SnapshotTime_SnapshotTimeType_name, int32(x))
}

func (SnapshotTime_SnapshotTimeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_87cc5ddaa298b2e3, []int{6, 0}
}

type AttributePredicate_PredicateType int32

const (
	AttributePredicate_ISNULL    AttributePredicate_PredicateType = 0
	AttributePredicate_ISNOTNULL AttributePredicate_PredicateType = 1
	AttributePredicate_RANGE     AttributePredicate_PredicateType = 2
)

var AttributePredicate_PredicateType_name = map[int32]string{
	0: "ISNULL",
	1: "ISNOTNULL",
	2: "RANGE",
}

var AttributePredicate_PredicateType_value = map[string]int32{
	"ISNULL":    0,
	"ISNOTNULL": 1,
	"RANGE":     2,
}

func (x AttributePredicate_PredicateType) String() string {
	return proto.EnumName(AttributePredicate_PredicateType_name, int32(x))
}

func (AttributePredicate_PredicateType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_87cc5ddaa298b2e3, []int{8, 0}
}

type LogOperation struct {
	ObjectId             string       `protobuf:"bytes,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	Bucket               string       `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Timestamp            *Vectorclock `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Payload              *Payload     `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *LogOperation) Reset()         { *m = LogOperation{} }
func (m *LogOperation) String() string { return proto.CompactTextString(m) }
func (*LogOperation) ProtoMessage()    {}
func (*LogOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_87cc5ddaa298b2e3, []int{0}
}

func (m *LogOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogOperation.Unmarshal(m, b)
}
func (m *LogOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogOperation.Marshal(b, m, deterministic)
}
func (m *LogOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogOperation.Merge(m, src)
}
func (m *LogOperation) XXX_Size() int {
	return xxx_messageInfo_LogOperation.Size(m)
}
func (m *LogOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_LogOperation.DiscardUnknown(m)
}

var xxx_messageInfo_LogOperation proto.InternalMessageInfo

func (m *LogOperation) GetObjectId() string {
	if m != nil {
		return m.ObjectId
	}
	return ""
}

func (m *LogOperation) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *LogOperation) GetTimestamp() *Vectorclock {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *LogOperation) GetPayload() *Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

type Payload struct {
	// Types that are valid to be assigned to Val:
	//	*Payload_Delta
	//	*Payload_Op
	//	*Payload_State
	Val                  isPayload_Val `protobuf_oneof:"val"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Payload) Reset()         { *m = Payload{} }
func (m *Payload) String() string { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()    {}
func (*Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_87cc5ddaa298b2e3, []int{1}
}

func (m *Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload.Unmarshal(m, b)
}
func (m *Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload.Marshal(b, m, deterministic)
}
func (m *Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload.Merge(m, src)
}
func (m *Payload) XXX_Size() int {
	return xxx_messageInfo_Payload.Size(m)
}
func (m *Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_Payload proto.InternalMessageInfo

type isPayload_Val interface {
	isPayload_Val()
}

type Payload_Delta struct {
	Delta *Payload_StateDelta `protobuf:"bytes,1,opt,name=delta,proto3,oneof"`
}

type Payload_Op struct {
	Op *Operation `protobuf:"bytes,2,opt,name=op,proto3,oneof"`
}

type Payload_State struct {
	State *ObjectState `protobuf:"bytes,3,opt,name=state,proto3,oneof"`
}

func (*Payload_Delta) isPayload_Val() {}

func (*Payload_Op) isPayload_Val() {}

func (*Payload_State) isPayload_Val() {}

func (m *Payload) GetVal() isPayload_Val {
	if m != nil {
		return m.Val
	}
	return nil
}

func (m *Payload) GetDelta() *Payload_StateDelta {
	if x, ok := m.GetVal().(*Payload_Delta); ok {
		return x.Delta
	}
	return nil
}

func (m *Payload) GetOp() *Operation {
	if x, ok := m.GetVal().(*Payload_Op); ok {
		return x.Op
	}
	return nil
}

func (m *Payload) GetState() *ObjectState {
	if x, ok := m.GetVal().(*Payload_State); ok {
		return x.State
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Payload) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Payload_Delta)(nil),
		(*Payload_Op)(nil),
		(*Payload_State)(nil),
	}
}

type Payload_StateDelta struct {
	Old                  *ObjectState `protobuf:"bytes,1,opt,name=old,proto3" json:"old,omitempty"`
	New                  *ObjectState `protobuf:"bytes,2,opt,name=new,proto3" json:"new,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Payload_StateDelta) Reset()         { *m = Payload_StateDelta{} }
func (m *Payload_StateDelta) String() string { return proto.CompactTextString(m) }
func (*Payload_StateDelta) ProtoMessage()    {}
func (*Payload_StateDelta) Descriptor() ([]byte, []int) {
	return fileDescriptor_87cc5ddaa298b2e3, []int{1, 0}
}

func (m *Payload_StateDelta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload_StateDelta.Unmarshal(m, b)
}
func (m *Payload_StateDelta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload_StateDelta.Marshal(b, m, deterministic)
}
func (m *Payload_StateDelta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload_StateDelta.Merge(m, src)
}
func (m *Payload_StateDelta) XXX_Size() int {
	return xxx_messageInfo_Payload_StateDelta.Size(m)
}
func (m *Payload_StateDelta) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload_StateDelta.DiscardUnknown(m)
}

var xxx_messageInfo_Payload_StateDelta proto.InternalMessageInfo

func (m *Payload_StateDelta) GetOld() *ObjectState {
	if m != nil {
		return m.Old
	}
	return nil
}

func (m *Payload_StateDelta) GetNew() *ObjectState {
	if m != nil {
		return m.New
	}
	return nil
}

type ObjectState struct {
	Attributes           map[string]*Value `protobuf:"bytes,1,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ObjectState) Reset()         { *m = ObjectState{} }
func (m *ObjectState) String() string { return proto.CompactTextString(m) }
func (*ObjectState) ProtoMessage()    {}
func (*ObjectState) Descriptor() ([]byte, []int) {
	return fileDescriptor_87cc5ddaa298b2e3, []int{2}
}

func (m *ObjectState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectState.Unmarshal(m, b)
}
func (m *ObjectState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectState.Marshal(b, m, deterministic)
}
func (m *ObjectState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectState.Merge(m, src)
}
func (m *ObjectState) XXX_Size() int {
	return xxx_messageInfo_ObjectState.Size(m)
}
func (m *ObjectState) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectState.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectState proto.InternalMessageInfo

func (m *ObjectState) GetAttributes() map[string]*Value {
	if m != nil {
		return m.Attributes
	}
	return nil
}

type Operation struct {
	Op                   []*Operation_Op `protobuf:"bytes,1,rep,name=op,proto3" json:"op,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Operation) Reset()         { *m = Operation{} }
func (m *Operation) String() string { return proto.CompactTextString(m) }
func (*Operation) ProtoMessage()    {}
func (*Operation) Descriptor() ([]byte, []int) {
	return fileDescriptor_87cc5ddaa298b2e3, []int{3}
}

func (m *Operation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Operation.Unmarshal(m, b)
}
func (m *Operation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Operation.Marshal(b, m, deterministic)
}
func (m *Operation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Operation.Merge(m, src)
}
func (m *Operation) XXX_Size() int {
	return xxx_messageInfo_Operation.Size(m)
}
func (m *Operation) XXX_DiscardUnknown() {
	xxx_messageInfo_Operation.DiscardUnknown(m)
}

var xxx_messageInfo_Operation proto.InternalMessageInfo

func (m *Operation) GetOp() []*Operation_Op {
	if m != nil {
		return m.Op
	}
	return nil
}

type Operation_Update struct {
	OpType               string   `protobuf:"bytes,1,opt,name=op_type,json=opType,proto3" json:"op_type,omitempty"`
	Value                *Value   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Operation_Update) Reset()         { *m = Operation_Update{} }
func (m *Operation_Update) String() string { return proto.CompactTextString(m) }
func (*Operation_Update) ProtoMessage()    {}
func (*Operation_Update) Descriptor() ([]byte, []int) {
	return fileDescriptor_87cc5ddaa298b2e3, []int{3, 0}
}

func (m *Operation_Update) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Operation_Update.Unmarshal(m, b)
}
func (m *Operation_Update) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Operation_Update.Marshal(b, m, deterministic)
}
func (m *Operation_Update) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Operation_Update.Merge(m, src)
}
func (m *Operation_Update) XXX_Size() int {
	return xxx_messageInfo_Operation_Update.Size(m)
}
func (m *Operation_Update) XXX_DiscardUnknown() {
	xxx_messageInfo_Operation_Update.DiscardUnknown(m)
}

var xxx_messageInfo_Operation_Update proto.InternalMessageInfo

func (m *Operation_Update) GetOpType() string {
	if m != nil {
		return m.OpType
	}
	return ""
}

func (m *Operation_Update) GetValue() *Value {
	if m != nil {
		return m.Value
	}
	return nil
}

type Operation_Op struct {
	Attr                 *Attribute        `protobuf:"bytes,1,opt,name=attr,proto3" json:"attr,omitempty"`
	Update               *Operation_Update `protobuf:"bytes,2,opt,name=update,proto3" json:"update,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Operation_Op) Reset()         { *m = Operation_Op{} }
func (m *Operation_Op) String() string { return proto.CompactTextString(m) }
func (*Operation_Op) ProtoMessage()    {}
func (*Operation_Op) Descriptor() ([]byte, []int) {
	return fileDescriptor_87cc5ddaa298b2e3, []int{3, 1}
}

func (m *Operation_Op) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Operation_Op.Unmarshal(m, b)
}
func (m *Operation_Op) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Operation_Op.Marshal(b, m, deterministic)
}
func (m *Operation_Op) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Operation_Op.Merge(m, src)
}
func (m *Operation_Op) XXX_Size() int {
	return xxx_messageInfo_Operation_Op.Size(m)
}
func (m *Operation_Op) XXX_DiscardUnknown() {
	xxx_messageInfo_Operation_Op.DiscardUnknown(m)
}

var xxx_messageInfo_Operation_Op proto.InternalMessageInfo

func (m *Operation_Op) GetAttr() *Attribute {
	if m != nil {
		return m.Attr
	}
	return nil
}

func (m *Operation_Op) GetUpdate() *Operation_Update {
	if m != nil {
		return m.Update
	}
	return nil
}

type Attribute struct {
	AttrKey              string   `protobuf:"bytes,1,opt,name=attr_key,json=attrKey,proto3" json:"attr_key,omitempty"`
	Value                *Value   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Attribute) Reset()         { *m = Attribute{} }
func (m *Attribute) String() string { return proto.CompactTextString(m) }
func (*Attribute) ProtoMessage()    {}
func (*Attribute) Descriptor() ([]byte, []int) {
	return fileDescriptor_87cc5ddaa298b2e3, []int{4}
}

func (m *Attribute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Attribute.Unmarshal(m, b)
}
func (m *Attribute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Attribute.Marshal(b, m, deterministic)
}
func (m *Attribute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attribute.Merge(m, src)
}
func (m *Attribute) XXX_Size() int {
	return xxx_messageInfo_Attribute.Size(m)
}
func (m *Attribute) XXX_DiscardUnknown() {
	xxx_messageInfo_Attribute.DiscardUnknown(m)
}

var xxx_messageInfo_Attribute proto.InternalMessageInfo

func (m *Attribute) GetAttrKey() string {
	if m != nil {
		return m.AttrKey
	}
	return ""
}

func (m *Attribute) GetValue() *Value {
	if m != nil {
		return m.Value
	}
	return nil
}

type Value struct {
	// Types that are valid to be assigned to Val:
	//	*Value_Str
	//	*Value_Int
	//	*Value_Flt
	Val                  isValue_Val `protobuf_oneof:"val"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_87cc5ddaa298b2e3, []int{5}
}

func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (m *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(m, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

type isValue_Val interface {
	isValue_Val()
}

type Value_Str struct {
	Str string `protobuf:"bytes,1,opt,name=str,proto3,oneof"`
}

type Value_Int struct {
	Int int64 `protobuf:"varint,2,opt,name=int,proto3,oneof"`
}

type Value_Flt struct {
	Flt float64 `protobuf:"fixed64,3,opt,name=flt,proto3,oneof"`
}

func (*Value_Str) isValue_Val() {}

func (*Value_Int) isValue_Val() {}

func (*Value_Flt) isValue_Val() {}

func (m *Value) GetVal() isValue_Val {
	if m != nil {
		return m.Val
	}
	return nil
}

func (m *Value) GetStr() string {
	if x, ok := m.GetVal().(*Value_Str); ok {
		return x.Str
	}
	return ""
}

func (m *Value) GetInt() int64 {
	if x, ok := m.GetVal().(*Value_Int); ok {
		return x.Int
	}
	return 0
}

func (m *Value) GetFlt() float64 {
	if x, ok := m.GetVal().(*Value_Flt); ok {
		return x.Flt
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Value) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Value_Str)(nil),
		(*Value_Int)(nil),
		(*Value_Flt)(nil),
	}
}

type SnapshotTime struct {
	Type                 SnapshotTime_SnapshotTimeType `protobuf:"varint,1,opt,name=type,proto3,enum=qpu.SnapshotTime_SnapshotTimeType" json:"type,omitempty"`
	Value                *Vectorclock                  `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	IsClosed             bool                          `protobuf:"varint,3,opt,name=isClosed,proto3" json:"isClosed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *SnapshotTime) Reset()         { *m = SnapshotTime{} }
func (m *SnapshotTime) String() string { return proto.CompactTextString(m) }
func (*SnapshotTime) ProtoMessage()    {}
func (*SnapshotTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_87cc5ddaa298b2e3, []int{6}
}

func (m *SnapshotTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SnapshotTime.Unmarshal(m, b)
}
func (m *SnapshotTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SnapshotTime.Marshal(b, m, deterministic)
}
func (m *SnapshotTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SnapshotTime.Merge(m, src)
}
func (m *SnapshotTime) XXX_Size() int {
	return xxx_messageInfo_SnapshotTime.Size(m)
}
func (m *SnapshotTime) XXX_DiscardUnknown() {
	xxx_messageInfo_SnapshotTime.DiscardUnknown(m)
}

var xxx_messageInfo_SnapshotTime proto.InternalMessageInfo

func (m *SnapshotTime) GetType() SnapshotTime_SnapshotTimeType {
	if m != nil {
		return m.Type
	}
	return SnapshotTime_LATEST
}

func (m *SnapshotTime) GetValue() *Vectorclock {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *SnapshotTime) GetIsClosed() bool {
	if m != nil {
		return m.IsClosed
	}
	return false
}

type Vectorclock struct {
	Vc                   map[string]*timestamp.Timestamp `protobuf:"bytes,1,rep,name=vc,proto3" json:"vc,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *Vectorclock) Reset()         { *m = Vectorclock{} }
func (m *Vectorclock) String() string { return proto.CompactTextString(m) }
func (*Vectorclock) ProtoMessage()    {}
func (*Vectorclock) Descriptor() ([]byte, []int) {
	return fileDescriptor_87cc5ddaa298b2e3, []int{7}
}

func (m *Vectorclock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vectorclock.Unmarshal(m, b)
}
func (m *Vectorclock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vectorclock.Marshal(b, m, deterministic)
}
func (m *Vectorclock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vectorclock.Merge(m, src)
}
func (m *Vectorclock) XXX_Size() int {
	return xxx_messageInfo_Vectorclock.Size(m)
}
func (m *Vectorclock) XXX_DiscardUnknown() {
	xxx_messageInfo_Vectorclock.DiscardUnknown(m)
}

var xxx_messageInfo_Vectorclock proto.InternalMessageInfo

func (m *Vectorclock) GetVc() map[string]*timestamp.Timestamp {
	if m != nil {
		return m.Vc
	}
	return nil
}

type AttributePredicate struct {
	Attr                 *Attribute                       `protobuf:"bytes,1,opt,name=attr,proto3" json:"attr,omitempty"`
	Type                 AttributePredicate_PredicateType `protobuf:"varint,2,opt,name=type,proto3,enum=qpu.AttributePredicate_PredicateType" json:"type,omitempty"`
	Lbound               *Value                           `protobuf:"bytes,3,opt,name=lbound,proto3" json:"lbound,omitempty"`
	Ubound               *Value                           `protobuf:"bytes,4,opt,name=ubound,proto3" json:"ubound,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *AttributePredicate) Reset()         { *m = AttributePredicate{} }
func (m *AttributePredicate) String() string { return proto.CompactTextString(m) }
func (*AttributePredicate) ProtoMessage()    {}
func (*AttributePredicate) Descriptor() ([]byte, []int) {
	return fileDescriptor_87cc5ddaa298b2e3, []int{8}
}

func (m *AttributePredicate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttributePredicate.Unmarshal(m, b)
}
func (m *AttributePredicate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttributePredicate.Marshal(b, m, deterministic)
}
func (m *AttributePredicate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttributePredicate.Merge(m, src)
}
func (m *AttributePredicate) XXX_Size() int {
	return xxx_messageInfo_AttributePredicate.Size(m)
}
func (m *AttributePredicate) XXX_DiscardUnknown() {
	xxx_messageInfo_AttributePredicate.DiscardUnknown(m)
}

var xxx_messageInfo_AttributePredicate proto.InternalMessageInfo

func (m *AttributePredicate) GetAttr() *Attribute {
	if m != nil {
		return m.Attr
	}
	return nil
}

func (m *AttributePredicate) GetType() AttributePredicate_PredicateType {
	if m != nil {
		return m.Type
	}
	return AttributePredicate_ISNULL
}

func (m *AttributePredicate) GetLbound() *Value {
	if m != nil {
		return m.Lbound
	}
	return nil
}

func (m *AttributePredicate) GetUbound() *Value {
	if m != nil {
		return m.Ubound
	}
	return nil
}

type SnapshotTimePredicate struct {
	Lbound               *SnapshotTime `protobuf:"bytes,1,opt,name=lbound,proto3" json:"lbound,omitempty"`
	Ubound               *SnapshotTime `protobuf:"bytes,2,opt,name=ubound,proto3" json:"ubound,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SnapshotTimePredicate) Reset()         { *m = SnapshotTimePredicate{} }
func (m *SnapshotTimePredicate) String() string { return proto.CompactTextString(m) }
func (*SnapshotTimePredicate) ProtoMessage()    {}
func (*SnapshotTimePredicate) Descriptor() ([]byte, []int) {
	return fileDescriptor_87cc5ddaa298b2e3, []int{9}
}

func (m *SnapshotTimePredicate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SnapshotTimePredicate.Unmarshal(m, b)
}
func (m *SnapshotTimePredicate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SnapshotTimePredicate.Marshal(b, m, deterministic)
}
func (m *SnapshotTimePredicate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SnapshotTimePredicate.Merge(m, src)
}
func (m *SnapshotTimePredicate) XXX_Size() int {
	return xxx_messageInfo_SnapshotTimePredicate.Size(m)
}
func (m *SnapshotTimePredicate) XXX_DiscardUnknown() {
	xxx_messageInfo_SnapshotTimePredicate.DiscardUnknown(m)
}

var xxx_messageInfo_SnapshotTimePredicate proto.InternalMessageInfo

func (m *SnapshotTimePredicate) GetLbound() *SnapshotTime {
	if m != nil {
		return m.Lbound
	}
	return nil
}

func (m *SnapshotTimePredicate) GetUbound() *SnapshotTime {
	if m != nil {
		return m.Ubound
	}
	return nil
}

func init() {
	proto.RegisterEnum("qpu.SnapshotTime_SnapshotTimeType", SnapshotTime_SnapshotTimeType_name, SnapshotTime_SnapshotTimeType_value)
	proto.RegisterEnum("qpu.AttributePredicate_PredicateType", AttributePredicate_PredicateType_name, AttributePredicate_PredicateType_value)
	proto.RegisterType((*LogOperation)(nil), "qpu.LogOperation")
	proto.RegisterType((*Payload)(nil), "qpu.Payload")
	proto.RegisterType((*Payload_StateDelta)(nil), "qpu.Payload.StateDelta")
	proto.RegisterType((*ObjectState)(nil), "qpu.ObjectState")
	proto.RegisterMapType((map[string]*Value)(nil), "qpu.ObjectState.AttributesEntry")
	proto.RegisterType((*Operation)(nil), "qpu.Operation")
	proto.RegisterType((*Operation_Update)(nil), "qpu.Operation.Update")
	proto.RegisterType((*Operation_Op)(nil), "qpu.Operation.Op")
	proto.RegisterType((*Attribute)(nil), "qpu.Attribute")
	proto.RegisterType((*Value)(nil), "qpu.Value")
	proto.RegisterType((*SnapshotTime)(nil), "qpu.SnapshotTime")
	proto.RegisterType((*Vectorclock)(nil), "qpu.Vectorclock")
	proto.RegisterMapType((map[string]*timestamp.Timestamp)(nil), "qpu.Vectorclock.VcEntry")
	proto.RegisterType((*AttributePredicate)(nil), "qpu.AttributePredicate")
	proto.RegisterType((*SnapshotTimePredicate)(nil), "qpu.SnapshotTimePredicate")
}

func init() { proto.RegisterFile("api/protobuf-spec/qpu.proto", fileDescriptor_87cc5ddaa298b2e3) }

var fileDescriptor_87cc5ddaa298b2e3 = []byte{
	// 816 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0xdd, 0x8e, 0xdb, 0x44,
	0x14, 0x8e, 0xed, 0xfc, 0xf9, 0x64, 0xdb, 0xba, 0x23, 0x95, 0x06, 0xf7, 0x82, 0x60, 0x89, 0x2a,
	0xbd, 0xa8, 0x53, 0x05, 0x81, 0x80, 0x2b, 0x76, 0x43, 0x60, 0x43, 0xa3, 0xb8, 0x4c, 0xdc, 0x45,
	0xea, 0xcd, 0xca, 0xb1, 0x67, 0x53, 0xb3, 0x8e, 0x67, 0x1a, 0x8f, 0x53, 0xe5, 0x15, 0x78, 0x04,
	0x78, 0x25, 0xc4, 0x4b, 0xf0, 0x06, 0x3c, 0x01, 0x9a, 0x19, 0xc7, 0x71, 0x92, 0xad, 0xe8, 0x9d,
	0xcf, 0x39, 0xdf, 0x7c, 0xe7, 0x3b, 0x3f, 0x9e, 0x81, 0x27, 0x01, 0x8b, 0x07, 0x6c, 0x4d, 0x39,
	0x5d, 0xe4, 0x37, 0xcf, 0x33, 0x46, 0xc2, 0xc1, 0x3b, 0x96, 0xbb, 0xd2, 0x83, 0x8c, 0x77, 0x2c,
	0xb7, 0x3f, 0x5b, 0x52, 0xba, 0x4c, 0x48, 0x09, 0x1a, 0xf0, 0x78, 0x45, 0x32, 0x1e, 0xac, 0x98,
	0x42, 0x39, 0x7f, 0x6a, 0x70, 0x36, 0xa5, 0x4b, 0x8f, 0x91, 0x75, 0xc0, 0x63, 0x9a, 0xa2, 0x27,
	0x60, 0xd2, 0xc5, 0x6f, 0x24, 0xe4, 0xd7, 0x71, 0xd4, 0xd5, 0x7a, 0x5a, 0xdf, 0xc4, 0x6d, 0xe5,
	0x98, 0x44, 0xe8, 0x13, 0x68, 0x2e, 0xf2, 0xf0, 0x96, 0xf0, 0xae, 0x2e, 0x23, 0x85, 0x85, 0x5c,
	0x30, 0x4b, 0xe2, 0xae, 0xd1, 0xd3, 0xfa, 0x9d, 0xa1, 0xe5, 0x0a, 0x29, 0x57, 0x24, 0xe4, 0x74,
	0x1d, 0x26, 0x34, 0xbc, 0xc5, 0x7b, 0x08, 0x7a, 0x0a, 0x2d, 0x16, 0x6c, 0x13, 0x1a, 0x44, 0xdd,
	0xba, 0x44, 0x9f, 0x49, 0xf4, 0x2b, 0xe5, 0xc3, 0xbb, 0xa0, 0xf3, 0x8f, 0x06, 0xad, 0xc2, 0x89,
	0x06, 0xd0, 0x88, 0x48, 0xc2, 0x03, 0x29, 0xaa, 0x33, 0x7c, 0x5c, 0x3d, 0xe1, 0xce, 0x79, 0xc0,
	0xc9, 0x0f, 0x22, 0x7c, 0x59, 0xc3, 0x0a, 0x87, 0x7a, 0xa0, 0x53, 0x26, 0x85, 0x76, 0x86, 0xf7,
	0x25, 0xba, 0xac, 0xf2, 0xb2, 0x86, 0x75, 0xca, 0x50, 0x1f, 0x1a, 0x99, 0x38, 0x78, 0x20, 0xd9,
	0x93, 0xc5, 0x4a, 0x42, 0xc1, 0x25, 0x01, 0xb6, 0x0f, 0xb0, 0x4f, 0x81, 0x1c, 0x30, 0x68, 0x12,
	0x15, 0x42, 0x4e, 0x4e, 0x61, 0x11, 0x14, 0x98, 0x94, 0xbc, 0x2f, 0xd2, 0xdf, 0x81, 0x49, 0xc9,
	0xfb, 0x8b, 0x06, 0x18, 0x9b, 0x20, 0x71, 0xfe, 0xd0, 0xa0, 0x53, 0x89, 0xa1, 0xef, 0x01, 0x02,
	0xce, 0xd7, 0xf1, 0x22, 0xe7, 0x24, 0xeb, 0x6a, 0x3d, 0xa3, 0xdf, 0x19, 0xf6, 0x8e, 0x19, 0xdc,
	0xf3, 0x12, 0x32, 0x4e, 0xf9, 0x7a, 0x8b, 0x2b, 0x67, 0xec, 0x09, 0x3c, 0x38, 0x0a, 0x23, 0x0b,
	0x8c, 0x5b, 0xb2, 0x2d, 0x26, 0x2a, 0x3e, 0x51, 0x0f, 0x1a, 0x9b, 0x20, 0xc9, 0x49, 0xa1, 0x11,
	0xd4, 0xc0, 0x84, 0x07, 0xab, 0xc0, 0x77, 0xfa, 0x37, 0x9a, 0xf3, 0x97, 0x06, 0xe6, 0x7e, 0x3b,
	0x3e, 0x97, 0x3d, 0x55, 0x92, 0x1e, 0x1e, 0xf6, 0xd4, 0xf5, 0x98, 0x68, 0xaa, 0x3d, 0x82, 0xe6,
	0x6b, 0x16, 0x89, 0x3a, 0x1e, 0x43, 0x8b, 0xb2, 0x6b, 0xbe, 0x65, 0xa4, 0x48, 0xdb, 0xa4, 0xcc,
	0xdf, 0x32, 0xf2, 0xff, 0x99, 0xed, 0x5f, 0x41, 0xf7, 0x18, 0x72, 0xa0, 0x2e, 0x8a, 0x2a, 0x1a,
	0xad, 0x66, 0x58, 0xd6, 0x85, 0x65, 0x0c, 0x3d, 0x87, 0x66, 0x2e, 0xd3, 0x15, 0x64, 0x8f, 0x8e,
	0x54, 0x29, 0x2d, 0xb8, 0x00, 0x39, 0x97, 0x60, 0x96, 0x0c, 0xe8, 0x53, 0x68, 0x0b, 0x8e, 0xeb,
	0x7d, 0x63, 0x5a, 0xc2, 0x7e, 0x59, 0x6d, 0x8e, 0xf1, 0x01, 0x89, 0xce, 0xcf, 0xd0, 0x90, 0x36,
	0x42, 0x60, 0x64, 0x85, 0x48, 0xf3, 0xb2, 0x86, 0x85, 0x21, 0x7c, 0x71, 0xaa, 0xfe, 0x12, 0x43,
	0xf8, 0xe2, 0x94, 0x0b, 0xdf, 0x4d, 0xc2, 0x25, 0xa1, 0x26, 0x7c, 0x37, 0x09, 0xdf, 0x6d, 0xc0,
	0xdf, 0x1a, 0x9c, 0xcd, 0xd3, 0x80, 0x65, 0x6f, 0x29, 0xf7, 0xe3, 0x15, 0x41, 0x5f, 0x43, 0xbd,
	0xec, 0xdb, 0xfd, 0xa1, 0x23, 0xb3, 0x57, 0x01, 0x07, 0x86, 0xe8, 0x29, 0x96, 0x78, 0xf4, 0xf4,
	0xb0, 0xb3, 0xa7, 0x3f, 0xa1, 0x0a, 0x23, 0x1b, 0xda, 0x71, 0x36, 0x4a, 0x68, 0x46, 0x22, 0x29,
	0xa8, 0x8d, 0x4b, 0xdb, 0xb9, 0x00, 0xeb, 0x98, 0x1d, 0x01, 0x34, 0xa7, 0xe7, 0xfe, 0x78, 0xee,
	0x5b, 0x35, 0xd4, 0x86, 0xfa, 0x9b, 0x31, 0xf6, 0x2c, 0x0d, 0xb5, 0xc0, 0x98, 0xcc, 0x7e, 0xb4,
	0x74, 0xf4, 0x00, 0x3a, 0x57, 0xe3, 0x91, 0xef, 0xe1, 0xd1, 0xd4, 0x1b, 0xbd, 0xb4, 0x0c, 0xe7,
	0x77, 0x0d, 0x3a, 0x95, 0xb4, 0xa8, 0x0f, 0xfa, 0x26, 0x2c, 0xf6, 0xa6, 0x7b, 0x2c, 0xca, 0xbd,
	0x0a, 0xd5, 0x0a, 0xeb, 0x9b, 0xd0, 0xfe, 0x05, 0x5a, 0x85, 0x79, 0xc7, 0xca, 0xbe, 0x38, 0x2c,
	0xcf, 0x76, 0xd5, 0xf5, 0xe6, 0xee, 0xae, 0x37, 0xd7, 0xdf, 0x5d, 0x31, 0xd5, 0x15, 0xfe, 0x57,
	0x03, 0x54, 0x0e, 0xfd, 0xd5, 0x9a, 0x44, 0x71, 0x28, 0xd6, 0xf3, 0x63, 0xb6, 0xeb, 0xdb, 0x62,
	0x0e, 0xba, 0x9c, 0xc3, 0x17, 0x87, 0x98, 0x92, 0xca, 0x2d, 0xbf, 0x2a, 0xa3, 0x70, 0xa0, 0x99,
	0x2c, 0x68, 0x9e, 0x46, 0x77, 0xac, 0x50, 0x11, 0x11, 0x98, 0x5c, 0x61, 0xea, 0xa7, 0x18, 0x15,
	0x71, 0xbe, 0x82, 0x7b, 0x07, 0xf4, 0x62, 0x16, 0x93, 0xf9, 0xec, 0xf5, 0x74, 0x6a, 0xd5, 0xd0,
	0x3d, 0x30, 0x27, 0xf3, 0x99, 0xe7, 0x4b, 0x53, 0x43, 0x26, 0x34, 0xf0, 0xf9, 0xec, 0xa7, 0xb1,
	0xa5, 0x3b, 0x2b, 0x78, 0x54, 0x9d, 0xe2, 0xbe, 0xec, 0x67, 0xa5, 0x2e, 0x55, 0xf8, 0xc3, 0x93,
	0xe5, 0x2a, 0xe5, 0x3d, 0x2b, 0xe5, 0xe9, 0x1f, 0x84, 0x2a, 0xc0, 0xc5, 0x8b, 0x37, 0xee, 0x32,
	0xe6, 0x6f, 0xf3, 0x85, 0x1b, 0xd2, 0xd5, 0x20, 0xda, 0x04, 0x59, 0x9c, 0x04, 0x99, 0x7c, 0x77,
	0x48, 0x9e, 0x0d, 0xe2, 0x94, 0x93, 0x75, 0x1a, 0x24, 0xea, 0x21, 0x12, 0xaf, 0xd4, 0xa2, 0x29,
	0x3f, 0xbf, 0xfc, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x28, 0x11, 0x21, 0xc5, 0xc5, 0x06, 0x00, 0x00,
}
