// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/protobuf-spec/qpuapi.proto

package qpuapi

import (
	context "context"
	fmt "fmt"
	qpu "github.com/dvasilas/proteus/internal/proto/qpu"
	qpuextapi "github.com/dvasilas/proteus/internal/proto/qpuextapi"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OrderBy_Order int32

const (
	OrderBy_ASC  OrderBy_Order = 0
	OrderBy_DESC OrderBy_Order = 1
)

var OrderBy_Order_name = map[int32]string{
	0: "ASC",
	1: "DESC",
}

var OrderBy_Order_value = map[string]int32{
	"ASC":  0,
	"DESC": 1,
}

func (x OrderBy_Order) String() string {
	return proto.EnumName(OrderBy_Order_name, int32(x))
}

func (OrderBy_Order) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2c8d817a1a70da97, []int{7, 0}
}

type ResponseStreamRecord_StreamRecordType int32

const (
	// Not used for now.
	ResponseStreamRecord_UPDATEOP ResponseStreamRecord_StreamRecordType = 0
	// Respresents an update.
	// udpate = (value_before_update, value_after_update)
	ResponseStreamRecord_UPDATEDELTA ResponseStreamRecord_StreamRecordType = 1
	// Represents the state of a data item.
	ResponseStreamRecord_STATE ResponseStreamRecord_StreamRecordType = 2
	// Sometimes we exchange heartbeats in long-lived streams to make sure
	// the two parts are still alive and the connection is open.
	ResponseStreamRecord_HEARTBEAT ResponseStreamRecord_StreamRecordType = 3
	// It informs the receiver of the stream for the end of a 'getSnapshot'
	// query (all STATE records will be sent, but more UPDATEDELTA may follow).
	// It is missleading:
	// an END_OF_STREAM can be send in a steam, and the stream may then
	// continue being used (for UPDATEDELTA records).
	ResponseStreamRecord_END_OF_STREAM ResponseStreamRecord_StreamRecordType = 4
)

var ResponseStreamRecord_StreamRecordType_name = map[int32]string{
	0: "UPDATEOP",
	1: "UPDATEDELTA",
	2: "STATE",
	3: "HEARTBEAT",
	4: "END_OF_STREAM",
}

var ResponseStreamRecord_StreamRecordType_value = map[string]int32{
	"UPDATEOP":      0,
	"UPDATEDELTA":   1,
	"STATE":         2,
	"HEARTBEAT":     3,
	"END_OF_STREAM": 4,
}

func (x ResponseStreamRecord_StreamRecordType) String() string {
	return proto.EnumName(ResponseStreamRecord_StreamRecordType_name, int32(x))
}

func (ResponseStreamRecord_StreamRecordType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2c8d817a1a70da97, []int{8, 0}
}

type ConfigResponse_QPUType int32

const (
	ConfigResponse_DATASTORE_DRIVER ConfigResponse_QPUType = 0
	ConfigResponse_SUM              ConfigResponse_QPUType = 1
	ConfigResponse_JOIN             ConfigResponse_QPUType = 2
	ConfigResponse_INDEX            ConfigResponse_QPUType = 3
	ConfigResponse_CACHE            ConfigResponse_QPUType = 4
)

var ConfigResponse_QPUType_name = map[int32]string{
	0: "DATASTORE_DRIVER",
	1: "SUM",
	2: "JOIN",
	3: "INDEX",
	4: "CACHE",
}

var ConfigResponse_QPUType_value = map[string]int32{
	"DATASTORE_DRIVER": 0,
	"SUM":              1,
	"JOIN":             2,
	"INDEX":            3,
	"CACHE":            4,
}

func (x ConfigResponse_QPUType) String() string {
	return proto.EnumName(ConfigResponse_QPUType_name, int32(x))
}

func (ConfigResponse_QPUType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2c8d817a1a70da97, []int{11, 0}
}

type NoOpReq struct {
	Str                  string   `protobuf:"bytes,1,opt,name=str,proto3" json:"str,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoOpReq) Reset()         { *m = NoOpReq{} }
func (m *NoOpReq) String() string { return proto.CompactTextString(m) }
func (*NoOpReq) ProtoMessage()    {}
func (*NoOpReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c8d817a1a70da97, []int{0}
}

func (m *NoOpReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoOpReq.Unmarshal(m, b)
}
func (m *NoOpReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoOpReq.Marshal(b, m, deterministic)
}
func (m *NoOpReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoOpReq.Merge(m, src)
}
func (m *NoOpReq) XXX_Size() int {
	return xxx_messageInfo_NoOpReq.Size(m)
}
func (m *NoOpReq) XXX_DiscardUnknown() {
	xxx_messageInfo_NoOpReq.DiscardUnknown(m)
}

var xxx_messageInfo_NoOpReq proto.InternalMessageInfo

func (m *NoOpReq) GetStr() string {
	if m != nil {
		return m.Str
	}
	return ""
}

type NoOpResp struct {
	Str                  string   `protobuf:"bytes,1,opt,name=str,proto3" json:"str,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoOpResp) Reset()         { *m = NoOpResp{} }
func (m *NoOpResp) String() string { return proto.CompactTextString(m) }
func (*NoOpResp) ProtoMessage()    {}
func (*NoOpResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c8d817a1a70da97, []int{1}
}

func (m *NoOpResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoOpResp.Unmarshal(m, b)
}
func (m *NoOpResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoOpResp.Marshal(b, m, deterministic)
}
func (m *NoOpResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoOpResp.Merge(m, src)
}
func (m *NoOpResp) XXX_Size() int {
	return xxx_messageInfo_NoOpResp.Size(m)
}
func (m *NoOpResp) XXX_DiscardUnknown() {
	xxx_messageInfo_NoOpResp.DiscardUnknown(m)
}

var xxx_messageInfo_NoOpResp proto.InternalMessageInfo

func (m *NoOpResp) GetStr() string {
	if m != nil {
		return m.Str
	}
	return ""
}

type RequestStreamRecord struct {
	// Types that are valid to be assigned to Request:
	//	*RequestStreamRecord_QueryRequest
	//	*RequestStreamRecord_Ack
	Request              isRequestStreamRecord_Request `protobuf_oneof:"request"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *RequestStreamRecord) Reset()         { *m = RequestStreamRecord{} }
func (m *RequestStreamRecord) String() string { return proto.CompactTextString(m) }
func (*RequestStreamRecord) ProtoMessage()    {}
func (*RequestStreamRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c8d817a1a70da97, []int{2}
}

func (m *RequestStreamRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestStreamRecord.Unmarshal(m, b)
}
func (m *RequestStreamRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestStreamRecord.Marshal(b, m, deterministic)
}
func (m *RequestStreamRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestStreamRecord.Merge(m, src)
}
func (m *RequestStreamRecord) XXX_Size() int {
	return xxx_messageInfo_RequestStreamRecord.Size(m)
}
func (m *RequestStreamRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestStreamRecord.DiscardUnknown(m)
}

var xxx_messageInfo_RequestStreamRecord proto.InternalMessageInfo

type isRequestStreamRecord_Request interface {
	isRequestStreamRecord_Request()
}

type RequestStreamRecord_QueryRequest struct {
	QueryRequest *QueryRequest `protobuf:"bytes,1,opt,name=queryRequest,proto3,oneof"`
}

type RequestStreamRecord_Ack struct {
	Ack *AckMsg `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

func (*RequestStreamRecord_QueryRequest) isRequestStreamRecord_Request() {}

func (*RequestStreamRecord_Ack) isRequestStreamRecord_Request() {}

func (m *RequestStreamRecord) GetRequest() isRequestStreamRecord_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *RequestStreamRecord) GetQueryRequest() *QueryRequest {
	if x, ok := m.GetRequest().(*RequestStreamRecord_QueryRequest); ok {
		return x.QueryRequest
	}
	return nil
}

func (m *RequestStreamRecord) GetAck() *AckMsg {
	if x, ok := m.GetRequest().(*RequestStreamRecord_Ack); ok {
		return x.Ack
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*RequestStreamRecord) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*RequestStreamRecord_QueryRequest)(nil),
		(*RequestStreamRecord_Ack)(nil),
	}
}

type QueryRequest struct {
	Query    *Query            `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Metadata map[string]string `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Synchronous or asynhronous mode.
	// Only makes sence to use synchronous mode when the underlying datastore'
	// subscribe API has the ability to block updates waiting for acks.
	Sync                 bool     `protobuf:"varint,3,opt,name=sync,proto3" json:"sync,omitempty"`
	MeasureDataTransfer  bool     `protobuf:"varint,4,opt,name=measureDataTransfer,proto3" json:"measureDataTransfer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryRequest) Reset()         { *m = QueryRequest{} }
func (m *QueryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()    {}
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c8d817a1a70da97, []int{3}
}

func (m *QueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRequest.Unmarshal(m, b)
}
func (m *QueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRequest.Marshal(b, m, deterministic)
}
func (m *QueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRequest.Merge(m, src)
}
func (m *QueryRequest) XXX_Size() int {
	return xxx_messageInfo_QueryRequest.Size(m)
}
func (m *QueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRequest proto.InternalMessageInfo

func (m *QueryRequest) GetQuery() *Query {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *QueryRequest) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *QueryRequest) GetSync() bool {
	if m != nil {
		return m.Sync
	}
	return false
}

func (m *QueryRequest) GetMeasureDataTransfer() bool {
	if m != nil {
		return m.MeasureDataTransfer
	}
	return false
}

type Query struct {
	// Types that are valid to be assigned to Query:
	//	*Query_QueryAst
	//	*Query_QuerySql
	Query                isQuery_Query `protobuf_oneof:"query"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Query) Reset()         { *m = Query{} }
func (m *Query) String() string { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()    {}
func (*Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c8d817a1a70da97, []int{4}
}

func (m *Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Query.Unmarshal(m, b)
}
func (m *Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Query.Marshal(b, m, deterministic)
}
func (m *Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Query.Merge(m, src)
}
func (m *Query) XXX_Size() int {
	return xxx_messageInfo_Query.Size(m)
}
func (m *Query) XXX_DiscardUnknown() {
	xxx_messageInfo_Query.DiscardUnknown(m)
}

var xxx_messageInfo_Query proto.InternalMessageInfo

type isQuery_Query interface {
	isQuery_Query()
}

type Query_QueryAst struct {
	QueryAst *ASTQuery `protobuf:"bytes,1,opt,name=query_ast,json=queryAst,proto3,oneof"`
}

type Query_QuerySql struct {
	QuerySql *SQLQuery `protobuf:"bytes,2,opt,name=query_sql,json=querySql,proto3,oneof"`
}

func (*Query_QueryAst) isQuery_Query() {}

func (*Query_QuerySql) isQuery_Query() {}

func (m *Query) GetQuery() isQuery_Query {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *Query) GetQueryAst() *ASTQuery {
	if x, ok := m.GetQuery().(*Query_QueryAst); ok {
		return x.QueryAst
	}
	return nil
}

func (m *Query) GetQuerySql() *SQLQuery {
	if x, ok := m.GetQuery().(*Query_QuerySql); ok {
		return x.QuerySql
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Query) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Query_QueryAst)(nil),
		(*Query_QuerySql)(nil),
	}
}

type SQLQuery struct {
	QueryStr             string   `protobuf:"bytes,1,opt,name=queryStr,proto3" json:"queryStr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SQLQuery) Reset()         { *m = SQLQuery{} }
func (m *SQLQuery) String() string { return proto.CompactTextString(m) }
func (*SQLQuery) ProtoMessage()    {}
func (*SQLQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c8d817a1a70da97, []int{5}
}

func (m *SQLQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SQLQuery.Unmarshal(m, b)
}
func (m *SQLQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SQLQuery.Marshal(b, m, deterministic)
}
func (m *SQLQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SQLQuery.Merge(m, src)
}
func (m *SQLQuery) XXX_Size() int {
	return xxx_messageInfo_SQLQuery.Size(m)
}
func (m *SQLQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_SQLQuery.DiscardUnknown(m)
}

var xxx_messageInfo_SQLQuery proto.InternalMessageInfo

func (m *SQLQuery) GetQueryStr() string {
	if m != nil {
		return m.QueryStr
	}
	return ""
}

// Internal query representation.
type ASTQuery struct {
	Table string `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	// Like the SQL PROJECTION.
	Projection []string `protobuf:"bytes,2,rep,name=projection,proto3" json:"projection,omitempty"`
	// Like the SQL WHERE statement.
	Predicate []*qpu.AttributePredicate `protobuf:"bytes,3,rep,name=predicate,proto3" json:"predicate,omitempty"`
	// Timespamp predicate.
	// Has the same form as AttributePredicate, but it is separate simply
	// to allow as to refer to this with a specific name (tsPredicate).
	TsPredicate *qpu.SnapshotTimePredicate `protobuf:"bytes,4,opt,name=tsPredicate,proto3" json:"tsPredicate,omitempty"`
	OrderBy     *OrderBy                   `protobuf:"bytes,5,opt,name=orderBy,proto3" json:"orderBy,omitempty"`
	// Like the SQL LIMIT
	Limit                int64    `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ASTQuery) Reset()         { *m = ASTQuery{} }
func (m *ASTQuery) String() string { return proto.CompactTextString(m) }
func (*ASTQuery) ProtoMessage()    {}
func (*ASTQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c8d817a1a70da97, []int{6}
}

func (m *ASTQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ASTQuery.Unmarshal(m, b)
}
func (m *ASTQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ASTQuery.Marshal(b, m, deterministic)
}
func (m *ASTQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ASTQuery.Merge(m, src)
}
func (m *ASTQuery) XXX_Size() int {
	return xxx_messageInfo_ASTQuery.Size(m)
}
func (m *ASTQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_ASTQuery.DiscardUnknown(m)
}

var xxx_messageInfo_ASTQuery proto.InternalMessageInfo

func (m *ASTQuery) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *ASTQuery) GetProjection() []string {
	if m != nil {
		return m.Projection
	}
	return nil
}

func (m *ASTQuery) GetPredicate() []*qpu.AttributePredicate {
	if m != nil {
		return m.Predicate
	}
	return nil
}

func (m *ASTQuery) GetTsPredicate() *qpu.SnapshotTimePredicate {
	if m != nil {
		return m.TsPredicate
	}
	return nil
}

func (m *ASTQuery) GetOrderBy() *OrderBy {
	if m != nil {
		return m.OrderBy
	}
	return nil
}

func (m *ASTQuery) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type OrderBy struct {
	AttributeName        string        `protobuf:"bytes,1,opt,name=attributeName,proto3" json:"attributeName,omitempty"`
	Direction            OrderBy_Order `protobuf:"varint,2,opt,name=direction,proto3,enum=qpuapi.OrderBy_Order" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *OrderBy) Reset()         { *m = OrderBy{} }
func (m *OrderBy) String() string { return proto.CompactTextString(m) }
func (*OrderBy) ProtoMessage()    {}
func (*OrderBy) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c8d817a1a70da97, []int{7}
}

func (m *OrderBy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderBy.Unmarshal(m, b)
}
func (m *OrderBy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderBy.Marshal(b, m, deterministic)
}
func (m *OrderBy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderBy.Merge(m, src)
}
func (m *OrderBy) XXX_Size() int {
	return xxx_messageInfo_OrderBy.Size(m)
}
func (m *OrderBy) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderBy.DiscardUnknown(m)
}

var xxx_messageInfo_OrderBy proto.InternalMessageInfo

func (m *OrderBy) GetAttributeName() string {
	if m != nil {
		return m.AttributeName
	}
	return ""
}

func (m *OrderBy) GetDirection() OrderBy_Order {
	if m != nil {
		return m.Direction
	}
	return OrderBy_ASC
}

// A record for the stream returned by Query.
type ResponseStreamRecord struct {
	// This is here to be used for checking for gaps in the stream and for
	// ordering records per stream
	// (not yet implemented)
	SequenceId           int64                                 `protobuf:"varint,1,opt,name=sequence_id,json=sequenceId,proto3" json:"sequence_id,omitempty"`
	Type                 ResponseStreamRecord_StreamRecordType `protobuf:"varint,2,opt,name=type,proto3,enum=qpuapi.ResponseStreamRecord_StreamRecordType" json:"type,omitempty"`
	LogOp                *qpu.LogOperation                     `protobuf:"bytes,3,opt,name=logOp,proto3" json:"logOp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *ResponseStreamRecord) Reset()         { *m = ResponseStreamRecord{} }
func (m *ResponseStreamRecord) String() string { return proto.CompactTextString(m) }
func (*ResponseStreamRecord) ProtoMessage()    {}
func (*ResponseStreamRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c8d817a1a70da97, []int{8}
}

func (m *ResponseStreamRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseStreamRecord.Unmarshal(m, b)
}
func (m *ResponseStreamRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseStreamRecord.Marshal(b, m, deterministic)
}
func (m *ResponseStreamRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseStreamRecord.Merge(m, src)
}
func (m *ResponseStreamRecord) XXX_Size() int {
	return xxx_messageInfo_ResponseStreamRecord.Size(m)
}
func (m *ResponseStreamRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseStreamRecord.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseStreamRecord proto.InternalMessageInfo

func (m *ResponseStreamRecord) GetSequenceId() int64 {
	if m != nil {
		return m.SequenceId
	}
	return 0
}

func (m *ResponseStreamRecord) GetType() ResponseStreamRecord_StreamRecordType {
	if m != nil {
		return m.Type
	}
	return ResponseStreamRecord_UPDATEOP
}

func (m *ResponseStreamRecord) GetLogOp() *qpu.LogOperation {
	if m != nil {
		return m.LogOp
	}
	return nil
}

// Simplification of ResponseStreamRecord
// used for QueryUnary.
type QueryResponse struct {
	Results              []*qpu.LogOperation `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *QueryResponse) Reset()         { *m = QueryResponse{} }
func (m *QueryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()    {}
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c8d817a1a70da97, []int{9}
}

func (m *QueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResponse.Unmarshal(m, b)
}
func (m *QueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResponse.Marshal(b, m, deterministic)
}
func (m *QueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResponse.Merge(m, src)
}
func (m *QueryResponse) XXX_Size() int {
	return xxx_messageInfo_QueryResponse.Size(m)
}
func (m *QueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResponse proto.InternalMessageInfo

func (m *QueryResponse) GetResults() []*qpu.LogOperation {
	if m != nil {
		return m.Results
	}
	return nil
}

type ConfigRequest struct {
	// Just here for future use, not actually used.
	Clock                *qpu.SnapshotTimePredicate `protobuf:"bytes,1,opt,name=clock,proto3" json:"clock,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ConfigRequest) Reset()         { *m = ConfigRequest{} }
func (m *ConfigRequest) String() string { return proto.CompactTextString(m) }
func (*ConfigRequest) ProtoMessage()    {}
func (*ConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c8d817a1a70da97, []int{10}
}

func (m *ConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigRequest.Unmarshal(m, b)
}
func (m *ConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigRequest.Marshal(b, m, deterministic)
}
func (m *ConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigRequest.Merge(m, src)
}
func (m *ConfigRequest) XXX_Size() int {
	return xxx_messageInfo_ConfigRequest.Size(m)
}
func (m *ConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigRequest proto.InternalMessageInfo

func (m *ConfigRequest) GetClock() *qpu.SnapshotTimePredicate {
	if m != nil {
		return m.Clock
	}
	return nil
}

type ConfigResponse struct {
	QpuType              ConfigResponse_QPUType    `protobuf:"varint,1,opt,name=qpu_type,json=qpuType,proto3,enum=qpuapi.ConfigResponse_QPUType" json:"qpu_type,omitempty"`
	Schema               []string                  `protobuf:"bytes,2,rep,name=schema,proto3" json:"schema,omitempty"`
	SupportedQueries     []*qpu.AttributePredicate `protobuf:"bytes,3,rep,name=supportedQueries,proto3" json:"supportedQueries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ConfigResponse) Reset()         { *m = ConfigResponse{} }
func (m *ConfigResponse) String() string { return proto.CompactTextString(m) }
func (*ConfigResponse) ProtoMessage()    {}
func (*ConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c8d817a1a70da97, []int{11}
}

func (m *ConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigResponse.Unmarshal(m, b)
}
func (m *ConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigResponse.Marshal(b, m, deterministic)
}
func (m *ConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigResponse.Merge(m, src)
}
func (m *ConfigResponse) XXX_Size() int {
	return xxx_messageInfo_ConfigResponse.Size(m)
}
func (m *ConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigResponse proto.InternalMessageInfo

func (m *ConfigResponse) GetQpuType() ConfigResponse_QPUType {
	if m != nil {
		return m.QpuType
	}
	return ConfigResponse_DATASTORE_DRIVER
}

func (m *ConfigResponse) GetSchema() []string {
	if m != nil {
		return m.Schema
	}
	return nil
}

func (m *ConfigResponse) GetSupportedQueries() []*qpu.AttributePredicate {
	if m != nil {
		return m.SupportedQueries
	}
	return nil
}

type AckMsg struct {
	SequenceId           int64    `protobuf:"varint,1,opt,name=sequence_id,json=sequenceId,proto3" json:"sequence_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AckMsg) Reset()         { *m = AckMsg{} }
func (m *AckMsg) String() string { return proto.CompactTextString(m) }
func (*AckMsg) ProtoMessage()    {}
func (*AckMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c8d817a1a70da97, []int{12}
}

func (m *AckMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckMsg.Unmarshal(m, b)
}
func (m *AckMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckMsg.Marshal(b, m, deterministic)
}
func (m *AckMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckMsg.Merge(m, src)
}
func (m *AckMsg) XXX_Size() int {
	return xxx_messageInfo_AckMsg.Size(m)
}
func (m *AckMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_AckMsg.DiscardUnknown(m)
}

var xxx_messageInfo_AckMsg proto.InternalMessageInfo

func (m *AckMsg) GetSequenceId() int64 {
	if m != nil {
		return m.SequenceId
	}
	return 0
}

func init() {
	proto.RegisterEnum("qpuapi.OrderBy_Order", OrderBy_Order_name, OrderBy_Order_value)
	proto.RegisterEnum("qpuapi.ResponseStreamRecord_StreamRecordType", ResponseStreamRecord_StreamRecordType_name, ResponseStreamRecord_StreamRecordType_value)
	proto.RegisterEnum("qpuapi.ConfigResponse_QPUType", ConfigResponse_QPUType_name, ConfigResponse_QPUType_value)
	proto.RegisterType((*NoOpReq)(nil), "qpuapi.NoOpReq")
	proto.RegisterType((*NoOpResp)(nil), "qpuapi.NoOpResp")
	proto.RegisterType((*RequestStreamRecord)(nil), "qpuapi.RequestStreamRecord")
	proto.RegisterType((*QueryRequest)(nil), "qpuapi.QueryRequest")
	proto.RegisterMapType((map[string]string)(nil), "qpuapi.QueryRequest.MetadataEntry")
	proto.RegisterType((*Query)(nil), "qpuapi.Query")
	proto.RegisterType((*SQLQuery)(nil), "qpuapi.SQLQuery")
	proto.RegisterType((*ASTQuery)(nil), "qpuapi.ASTQuery")
	proto.RegisterType((*OrderBy)(nil), "qpuapi.OrderBy")
	proto.RegisterType((*ResponseStreamRecord)(nil), "qpuapi.ResponseStreamRecord")
	proto.RegisterType((*QueryResponse)(nil), "qpuapi.QueryResponse")
	proto.RegisterType((*ConfigRequest)(nil), "qpuapi.ConfigRequest")
	proto.RegisterType((*ConfigResponse)(nil), "qpuapi.ConfigResponse")
	proto.RegisterType((*AckMsg)(nil), "qpuapi.AckMsg")
}

func init() { proto.RegisterFile("api/protobuf-spec/qpuapi.proto", fileDescriptor_2c8d817a1a70da97) }

var fileDescriptor_2c8d817a1a70da97 = []byte{
	// 1113 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xcf, 0x73, 0xda, 0x46,
	0x14, 0x46, 0xfc, 0xe6, 0x11, 0x12, 0x65, 0xe3, 0x24, 0x14, 0x67, 0x52, 0x57, 0xed, 0xb4, 0x64,
	0x3a, 0xc1, 0x0e, 0x9e, 0xce, 0x34, 0x89, 0xa7, 0x33, 0x32, 0x28, 0x86, 0x0e, 0x06, 0x2c, 0xc9,
	0x69, 0xa7, 0x87, 0x32, 0x8b, 0x58, 0x63, 0xd5, 0x20, 0x89, 0xdd, 0x55, 0xa6, 0xdc, 0x3a, 0xd3,
	0x5b, 0xff, 0xdc, 0x1e, 0x7a, 0xee, 0x68, 0xf5, 0x03, 0xb0, 0xd5, 0xe4, 0xd0, 0x13, 0x7a, 0xef,
	0xfb, 0xde, 0xb7, 0x6f, 0xbf, 0x7d, 0x2b, 0x04, 0xcf, 0xb1, 0x67, 0x1f, 0x7a, 0xd4, 0xe5, 0xee,
	0xd4, 0xbf, 0x7a, 0xc9, 0x3c, 0x62, 0x1d, 0xae, 0x3c, 0x1f, 0x7b, 0x76, 0x4b, 0x24, 0x51, 0x31,
	0x8c, 0x1a, 0xfb, 0xa9, 0xbc, 0x90, 0xd4, 0xf8, 0x22, 0x15, 0x24, 0xbf, 0xf3, 0x44, 0x47, 0xd9,
	0x87, 0xd2, 0xd0, 0x1d, 0x79, 0x3a, 0x59, 0x21, 0x19, 0x72, 0x8c, 0xd3, 0xba, 0x74, 0x20, 0x35,
	0x2b, 0x7a, 0xf0, 0xa8, 0x3c, 0x83, 0x72, 0x08, 0x32, 0x2f, 0x05, 0xfd, 0x43, 0x82, 0x47, 0x3a,
	0x59, 0xf9, 0x84, 0x71, 0x83, 0x53, 0x82, 0x97, 0x3a, 0xb1, 0x5c, 0x3a, 0x43, 0x6f, 0xe0, 0xde,
	0xca, 0x27, 0x74, 0x1d, 0x61, 0xa2, 0xa4, 0xda, 0xde, 0x6b, 0x45, 0xfd, 0x5f, 0x6c, 0x61, 0xbd,
	0x8c, 0xbe, 0xc3, 0x45, 0x0a, 0xe4, 0xb0, 0x75, 0x53, 0xcf, 0x8a, 0x92, 0xfb, 0x71, 0x89, 0x6a,
	0xdd, 0x9c, 0xb3, 0x79, 0x2f, 0xa3, 0x07, 0xe0, 0x69, 0x05, 0x4a, 0x34, 0xa4, 0x2b, 0xff, 0x48,
	0x70, 0x6f, 0x5b, 0x0f, 0x7d, 0x09, 0x05, 0xa1, 0x17, 0x2d, 0x5a, 0xdb, 0x5d, 0x34, 0xc4, 0xd0,
	0x0f, 0x50, 0x5e, 0x12, 0x8e, 0x67, 0x98, 0xe3, 0x7a, 0xf6, 0x20, 0xd7, 0xac, 0xb6, 0x95, 0xb4,
	0xe6, 0x5a, 0xe7, 0x11, 0x49, 0x73, 0x38, 0x5d, 0xeb, 0x49, 0x0d, 0x42, 0x90, 0x67, 0x6b, 0xc7,
	0xaa, 0xe7, 0x0e, 0xa4, 0x66, 0x59, 0x17, 0xcf, 0xe8, 0x08, 0x1e, 0x2d, 0x09, 0x66, 0x3e, 0x25,
	0x5d, 0xcc, 0xb1, 0x49, 0xb1, 0xc3, 0xae, 0x08, 0xad, 0xe7, 0x05, 0x25, 0x0d, 0x6a, 0xbc, 0x85,
	0xda, 0xce, 0x02, 0x81, 0xc3, 0x37, 0x64, 0x1d, 0x3b, 0x7c, 0x43, 0xd6, 0x68, 0x0f, 0x0a, 0x1f,
	0xf0, 0xc2, 0x27, 0xc2, 0x8f, 0x8a, 0x1e, 0x06, 0x6f, 0xb2, 0xdf, 0x4b, 0x0a, 0x85, 0x82, 0x68,
	0x15, 0x1d, 0x42, 0x45, 0x6c, 0x6a, 0x82, 0x13, 0xa7, 0xe5, 0xc4, 0x36, 0xc3, 0x14, 0xa4, 0x5e,
	0x46, 0x2f, 0x0b, 0x92, 0xca, 0xf8, 0xa6, 0x80, 0xad, 0x16, 0x91, 0xcf, 0x49, 0x81, 0x71, 0x31,
	0xd8, 0x2d, 0x30, 0x56, 0x8b, 0xd3, 0x52, 0x64, 0xa9, 0xf2, 0x35, 0x94, 0x63, 0x02, 0x6a, 0x40,
	0x44, 0x48, 0x46, 0x22, 0x89, 0x83, 0x43, 0x29, 0xc7, 0x4b, 0x07, 0x5b, 0xe0, 0x78, 0xba, 0x20,
	0x11, 0x2b, 0x0c, 0xd0, 0x73, 0x00, 0x8f, 0xba, 0xbf, 0x11, 0x8b, 0xdb, 0xae, 0x23, 0xce, 0xa0,
	0xa2, 0x6f, 0x65, 0xd0, 0x77, 0x50, 0xf1, 0x28, 0x99, 0xd9, 0x16, 0xe6, 0xa4, 0x9e, 0x13, 0x47,
	0xf4, 0x34, 0x68, 0xb2, 0xa5, 0x72, 0x4e, 0xed, 0xa9, 0xcf, 0xc9, 0x38, 0x86, 0xf5, 0x0d, 0x13,
	0x9d, 0x40, 0x95, 0xb3, 0x04, 0x11, 0xe6, 0x57, 0xdb, 0x0d, 0x51, 0x68, 0x38, 0xd8, 0x63, 0xd7,
	0x2e, 0x37, 0xed, 0xe5, 0x56, 0xed, 0x36, 0x1d, 0xbd, 0x80, 0x92, 0x4b, 0x67, 0x84, 0x9e, 0xae,
	0xeb, 0x05, 0x51, 0xf9, 0x20, 0xf6, 0x65, 0x14, 0xa6, 0xf5, 0x18, 0x0f, 0x76, 0xb5, 0xb0, 0x97,
	0x36, 0xaf, 0x17, 0x0f, 0xa4, 0x66, 0x4e, 0x0f, 0x83, 0xe0, 0x42, 0x94, 0x22, 0x2a, 0xfa, 0x0a,
	0x6a, 0x38, 0xee, 0x75, 0x88, 0x97, 0xf1, 0xfe, 0x77, 0x93, 0xe8, 0x18, 0x2a, 0x33, 0x9b, 0x26,
	0x36, 0x48, 0xcd, 0xfb, 0xed, 0xc7, 0xb7, 0x16, 0x0d, 0x7f, 0xf5, 0x0d, 0x4f, 0x69, 0x40, 0x41,
	0xe4, 0x50, 0x09, 0x72, 0xaa, 0xd1, 0x91, 0x33, 0xa8, 0x0c, 0xf9, 0xae, 0x66, 0x74, 0x64, 0x49,
	0xf9, 0x33, 0x0b, 0x7b, 0xc1, 0x75, 0x75, 0x1d, 0x46, 0x76, 0x2e, 0xe5, 0xe7, 0x50, 0x65, 0xc1,
	0x58, 0x3b, 0x16, 0x99, 0xd8, 0x33, 0xd1, 0x4d, 0x4e, 0x87, 0x38, 0xd5, 0x9f, 0x21, 0x15, 0xf2,
	0x7c, 0xed, 0x91, 0xa8, 0x8b, 0x97, 0x71, 0x17, 0x69, 0x62, 0xad, 0xed, 0xc0, 0x5c, 0x7b, 0x44,
	0x17, 0xa5, 0xe8, 0x1b, 0x28, 0x2c, 0xdc, 0xf9, 0xc8, 0x13, 0x17, 0xa3, 0xda, 0x7e, 0x28, 0x8c,
	0x1f, 0x04, 0x19, 0x42, 0x71, 0xd0, 0xba, 0x1e, 0xe2, 0xca, 0xaf, 0x20, 0xdf, 0x96, 0x40, 0xf7,
	0xa0, 0x7c, 0x39, 0xee, 0xaa, 0xa6, 0x36, 0x1a, 0xcb, 0x19, 0xf4, 0x00, 0xaa, 0x61, 0xd4, 0xd5,
	0x06, 0xa6, 0x2a, 0x4b, 0xa8, 0x02, 0x05, 0xc3, 0x54, 0x4d, 0x4d, 0xce, 0xa2, 0x1a, 0x54, 0x7a,
	0x9a, 0xaa, 0x9b, 0xa7, 0x9a, 0x6a, 0xca, 0x39, 0xf4, 0x10, 0x6a, 0xda, 0xb0, 0x3b, 0x19, 0xbd,
	0x9b, 0x18, 0xa6, 0xae, 0xa9, 0xe7, 0x72, 0x5e, 0x39, 0x81, 0x5a, 0x74, 0x91, 0xc3, 0xe6, 0xd1,
	0xb7, 0xc1, 0x2b, 0x83, 0xf9, 0x0b, 0xce, 0xea, 0x92, 0x98, 0xa6, 0x94, 0xde, 0x62, 0x86, 0xa2,
	0x42, 0xad, 0xe3, 0x3a, 0x57, 0xf6, 0x3c, 0x7e, 0xa9, 0x1c, 0x41, 0xc1, 0x5a, 0xb8, 0xd6, 0x4d,
	0x74, 0xbf, 0x3e, 0x36, 0x50, 0x21, 0x51, 0xf9, 0x5b, 0x82, 0xfb, 0xb1, 0x46, 0xd4, 0xc2, 0x6b,
	0x28, 0xaf, 0x3c, 0x7f, 0x22, 0x3c, 0x96, 0x84, 0xc7, 0xcf, 0x63, 0x8f, 0x77, 0x99, 0xad, 0x8b,
	0xf1, 0xa5, 0x30, 0xb5, 0xb4, 0xf2, 0x7c, 0x61, 0xcd, 0x13, 0x28, 0x32, 0xeb, 0x9a, 0x2c, 0x71,
	0x74, 0x53, 0xa2, 0x08, 0x75, 0x40, 0x66, 0xbe, 0xe7, 0xb9, 0x94, 0x93, 0x59, 0xb0, 0x5f, 0x9b,
	0xb0, 0x4f, 0x5d, 0x96, 0x3b, 0x05, 0x4a, 0x0f, 0x4a, 0xd1, 0x82, 0x68, 0x0f, 0xe4, 0xae, 0x6a,
	0xaa, 0x86, 0x39, 0xd2, 0xb5, 0x49, 0x57, 0xef, 0xbf, 0xd7, 0x74, 0x39, 0x13, 0x4c, 0x99, 0x71,
	0x79, 0x2e, 0x4b, 0xc1, 0x94, 0xfd, 0x38, 0xea, 0x0f, 0xe5, 0x6c, 0x70, 0x18, 0xfd, 0x61, 0x57,
	0xfb, 0x59, 0xce, 0x05, 0x8f, 0x1d, 0xb5, 0xd3, 0xd3, 0xe4, 0xbc, 0xf2, 0x02, 0x8a, 0xe1, 0x8b,
	0xfa, 0x93, 0xc3, 0xd6, 0xfe, 0xab, 0x00, 0xc5, 0x8b, 0xf1, 0xa5, 0x3a, 0xee, 0xa3, 0x5e, 0xfc,
	0x26, 0xdb, 0xdf, 0x8c, 0xdc, 0x9d, 0xff, 0x94, 0xc6, 0xb3, 0x8f, 0xcd, 0xa3, 0x92, 0x69, 0x4a,
	0x47, 0x12, 0x7a, 0x0d, 0x20, 0x94, 0x2e, 0x1d, 0x4c, 0xd7, 0xe8, 0x51, 0x6b, 0xf3, 0x57, 0x17,
	0xbf, 0xd5, 0x1b, 0x7b, 0x77, 0x93, 0xcc, 0x53, 0x32, 0xe8, 0x2d, 0x54, 0x37, 0xa5, 0xaf, 0xd2,
	0x6b, 0x1f, 0xa7, 0xd5, 0xbe, 0x52, 0x32, 0xe8, 0x04, 0x2a, 0x67, 0x84, 0x87, 0x87, 0x88, 0x1e,
	0xdf, 0x3e, 0x54, 0xb1, 0x97, 0xc6, 0x93, 0xf4, 0xb3, 0x56, 0x32, 0x48, 0x03, 0x38, 0x23, 0xfc,
	0x9c, 0x70, 0x6a, 0x5b, 0x0c, 0x7d, 0xb6, 0xb5, 0x48, 0x94, 0x8b, 0x25, 0x1a, 0x69, 0x50, 0x22,
	0xd3, 0x81, 0xea, 0x19, 0xe1, 0x3f, 0x51, 0x9b, 0x93, 0x81, 0x3b, 0xdf, 0xd1, 0xd9, 0xca, 0xdf,
	0xde, 0x47, 0x9c, 0x1f, 0x79, 0x4a, 0xe6, 0x48, 0x42, 0x43, 0x78, 0x38, 0x70, 0xa7, 0x8c, 0x13,
	0xca, 0xde, 0x51, 0xd7, 0xe1, 0x1e, 0x9e, 0x13, 0xb4, 0xbd, 0xee, 0xc0, 0x9d, 0x26, 0x40, 0xa0,
	0xb5, 0xff, 0x9f, 0x98, 0xb0, 0x75, 0x4b, 0xcf, 0xe0, 0x2e, 0x5d, 0xbf, 0x77, 0xf9, 0x1d, 0xbd,
	0x04, 0x48, 0xd1, 0xdb, 0xc2, 0x84, 0x9e, 0x09, 0x4f, 0xef, 0xe8, 0xf5, 0x1d, 0x46, 0x28, 0xff,
	0x1f, 0xaa, 0xa7, 0xc7, 0xbf, 0xbc, 0x9a, 0xdb, 0xfc, 0xda, 0x9f, 0xb6, 0x2c, 0x77, 0x79, 0x38,
	0xfb, 0x80, 0x99, 0xbd, 0xc0, 0x4c, 0x7c, 0x37, 0x11, 0x9f, 0x1d, 0xda, 0x0e, 0x27, 0xd4, 0xc1,
	0x8b, 0xf0, 0x43, 0x2a, 0xfa, 0x0a, 0x9b, 0x16, 0x45, 0x74, 0xfc, 0x6f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x45, 0x72, 0x57, 0xa5, 0xa8, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QPUAPIClient is the client API for QPUAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QPUAPIClient interface {
	// The QPU Query API.
	Query(ctx context.Context, opts ...grpc.CallOption) (QPUAPI_QueryClient, error)
	// QueryUnary is a simplification of Query that returns a single response
	// instead of a stream.
	// It is used to simplify the client code for clients that have queries
	// that look like SELECT .. FROM .. WHERE .. LIMIT N
	// and so do not care about streaming anyways.
	QueryUnary(ctx context.Context, in *qpuextapi.QueryReq, opts ...grpc.CallOption) (*qpuextapi.QueryResp, error)
	QueryUnary1(ctx context.Context, in *qpuextapi.QueryReq, opts ...grpc.CallOption) (*qpuextapi.QueryResp1, error)
	// The QPU GetConfig API.
	// Used by a 'parent' QPU to request the configuration and query processing
	// capabilities of a 'child` QPU.
	GetConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error)
	// QPUs implemement a mechanism for measuring the traffic between them
	// (each QPU measuring the total size of outbound messages)
	// GetDataTransfer was used for getting this measuremrents.
	// Disabled for now.
	// rpc GetDataTransfer(GetDataRequest) returns (DataTransferResponse) {}
	// rpc QueryNoOp(NoOpReq) returns (NoOpResp) {}
	// rpc QueryArgs(QueryRequest) returns (QueryResponse) {}
	GetMetrics(ctx context.Context, in *qpuextapi.MetricsRequest, opts ...grpc.CallOption) (*qpuextapi.MetricsResponse, error)
	GetWriteLog(ctx context.Context, in *qpuextapi.GetWriteLogReq, opts ...grpc.CallOption) (QPUAPI_GetWriteLogClient, error)
	LobstersFrontpage(ctx context.Context, in *qpuextapi.LobFrontpageReq, opts ...grpc.CallOption) (*qpuextapi.LobFrontpageResp, error)
	LobstersStoryVote(ctx context.Context, in *qpuextapi.LobStoryVoteReq, opts ...grpc.CallOption) (*qpuextapi.LobStoryVoteResp, error)
	LobstersStoryVoteInsert(ctx context.Context, in *qpuextapi.LobStoryVoteReq, opts ...grpc.CallOption) (*qpuextapi.LobStoryVoteResp, error)
}

type qPUAPIClient struct {
	cc *grpc.ClientConn
}

func NewQPUAPIClient(cc *grpc.ClientConn) QPUAPIClient {
	return &qPUAPIClient{cc}
}

func (c *qPUAPIClient) Query(ctx context.Context, opts ...grpc.CallOption) (QPUAPI_QueryClient, error) {
	stream, err := c.cc.NewStream(ctx, &_QPUAPI_serviceDesc.Streams[0], "/qpuapi.QPUAPI/Query", opts...)
	if err != nil {
		return nil, err
	}
	x := &qPUAPIQueryClient{stream}
	return x, nil
}

type QPUAPI_QueryClient interface {
	Send(*RequestStreamRecord) error
	Recv() (*ResponseStreamRecord, error)
	grpc.ClientStream
}

type qPUAPIQueryClient struct {
	grpc.ClientStream
}

func (x *qPUAPIQueryClient) Send(m *RequestStreamRecord) error {
	return x.ClientStream.SendMsg(m)
}

func (x *qPUAPIQueryClient) Recv() (*ResponseStreamRecord, error) {
	m := new(ResponseStreamRecord)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *qPUAPIClient) QueryUnary(ctx context.Context, in *qpuextapi.QueryReq, opts ...grpc.CallOption) (*qpuextapi.QueryResp, error) {
	out := new(qpuextapi.QueryResp)
	err := c.cc.Invoke(ctx, "/qpuapi.QPUAPI/QueryUnary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qPUAPIClient) QueryUnary1(ctx context.Context, in *qpuextapi.QueryReq, opts ...grpc.CallOption) (*qpuextapi.QueryResp1, error) {
	out := new(qpuextapi.QueryResp1)
	err := c.cc.Invoke(ctx, "/qpuapi.QPUAPI/QueryUnary1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qPUAPIClient) GetConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error) {
	out := new(ConfigResponse)
	err := c.cc.Invoke(ctx, "/qpuapi.QPUAPI/GetConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qPUAPIClient) GetMetrics(ctx context.Context, in *qpuextapi.MetricsRequest, opts ...grpc.CallOption) (*qpuextapi.MetricsResponse, error) {
	out := new(qpuextapi.MetricsResponse)
	err := c.cc.Invoke(ctx, "/qpuapi.QPUAPI/GetMetrics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qPUAPIClient) GetWriteLog(ctx context.Context, in *qpuextapi.GetWriteLogReq, opts ...grpc.CallOption) (QPUAPI_GetWriteLogClient, error) {
	stream, err := c.cc.NewStream(ctx, &_QPUAPI_serviceDesc.Streams[1], "/qpuapi.QPUAPI/GetWriteLog", opts...)
	if err != nil {
		return nil, err
	}
	x := &qPUAPIGetWriteLogClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type QPUAPI_GetWriteLogClient interface {
	Recv() (*qpuextapi.WriteLogOp, error)
	grpc.ClientStream
}

type qPUAPIGetWriteLogClient struct {
	grpc.ClientStream
}

func (x *qPUAPIGetWriteLogClient) Recv() (*qpuextapi.WriteLogOp, error) {
	m := new(qpuextapi.WriteLogOp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *qPUAPIClient) LobstersFrontpage(ctx context.Context, in *qpuextapi.LobFrontpageReq, opts ...grpc.CallOption) (*qpuextapi.LobFrontpageResp, error) {
	out := new(qpuextapi.LobFrontpageResp)
	err := c.cc.Invoke(ctx, "/qpuapi.QPUAPI/LobstersFrontpage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qPUAPIClient) LobstersStoryVote(ctx context.Context, in *qpuextapi.LobStoryVoteReq, opts ...grpc.CallOption) (*qpuextapi.LobStoryVoteResp, error) {
	out := new(qpuextapi.LobStoryVoteResp)
	err := c.cc.Invoke(ctx, "/qpuapi.QPUAPI/LobstersStoryVote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qPUAPIClient) LobstersStoryVoteInsert(ctx context.Context, in *qpuextapi.LobStoryVoteReq, opts ...grpc.CallOption) (*qpuextapi.LobStoryVoteResp, error) {
	out := new(qpuextapi.LobStoryVoteResp)
	err := c.cc.Invoke(ctx, "/qpuapi.QPUAPI/LobstersStoryVoteInsert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QPUAPIServer is the server API for QPUAPI service.
type QPUAPIServer interface {
	// The QPU Query API.
	Query(QPUAPI_QueryServer) error
	// QueryUnary is a simplification of Query that returns a single response
	// instead of a stream.
	// It is used to simplify the client code for clients that have queries
	// that look like SELECT .. FROM .. WHERE .. LIMIT N
	// and so do not care about streaming anyways.
	QueryUnary(context.Context, *qpuextapi.QueryReq) (*qpuextapi.QueryResp, error)
	QueryUnary1(context.Context, *qpuextapi.QueryReq) (*qpuextapi.QueryResp1, error)
	// The QPU GetConfig API.
	// Used by a 'parent' QPU to request the configuration and query processing
	// capabilities of a 'child` QPU.
	GetConfig(context.Context, *ConfigRequest) (*ConfigResponse, error)
	// QPUs implemement a mechanism for measuring the traffic between them
	// (each QPU measuring the total size of outbound messages)
	// GetDataTransfer was used for getting this measuremrents.
	// Disabled for now.
	// rpc GetDataTransfer(GetDataRequest) returns (DataTransferResponse) {}
	// rpc QueryNoOp(NoOpReq) returns (NoOpResp) {}
	// rpc QueryArgs(QueryRequest) returns (QueryResponse) {}
	GetMetrics(context.Context, *qpuextapi.MetricsRequest) (*qpuextapi.MetricsResponse, error)
	GetWriteLog(*qpuextapi.GetWriteLogReq, QPUAPI_GetWriteLogServer) error
	LobstersFrontpage(context.Context, *qpuextapi.LobFrontpageReq) (*qpuextapi.LobFrontpageResp, error)
	LobstersStoryVote(context.Context, *qpuextapi.LobStoryVoteReq) (*qpuextapi.LobStoryVoteResp, error)
	LobstersStoryVoteInsert(context.Context, *qpuextapi.LobStoryVoteReq) (*qpuextapi.LobStoryVoteResp, error)
}

func RegisterQPUAPIServer(s *grpc.Server, srv QPUAPIServer) {
	s.RegisterService(&_QPUAPI_serviceDesc, srv)
}

func _QPUAPI_Query_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(QPUAPIServer).Query(&qPUAPIQueryServer{stream})
}

type QPUAPI_QueryServer interface {
	Send(*ResponseStreamRecord) error
	Recv() (*RequestStreamRecord, error)
	grpc.ServerStream
}

type qPUAPIQueryServer struct {
	grpc.ServerStream
}

func (x *qPUAPIQueryServer) Send(m *ResponseStreamRecord) error {
	return x.ServerStream.SendMsg(m)
}

func (x *qPUAPIQueryServer) Recv() (*RequestStreamRecord, error) {
	m := new(RequestStreamRecord)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _QPUAPI_QueryUnary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(qpuextapi.QueryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QPUAPIServer).QueryUnary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qpuapi.QPUAPI/QueryUnary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QPUAPIServer).QueryUnary(ctx, req.(*qpuextapi.QueryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _QPUAPI_QueryUnary1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(qpuextapi.QueryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QPUAPIServer).QueryUnary1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qpuapi.QPUAPI/QueryUnary1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QPUAPIServer).QueryUnary1(ctx, req.(*qpuextapi.QueryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _QPUAPI_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QPUAPIServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qpuapi.QPUAPI/GetConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QPUAPIServer).GetConfig(ctx, req.(*ConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QPUAPI_GetMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(qpuextapi.MetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QPUAPIServer).GetMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qpuapi.QPUAPI/GetMetrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QPUAPIServer).GetMetrics(ctx, req.(*qpuextapi.MetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QPUAPI_GetWriteLog_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(qpuextapi.GetWriteLogReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QPUAPIServer).GetWriteLog(m, &qPUAPIGetWriteLogServer{stream})
}

type QPUAPI_GetWriteLogServer interface {
	Send(*qpuextapi.WriteLogOp) error
	grpc.ServerStream
}

type qPUAPIGetWriteLogServer struct {
	grpc.ServerStream
}

func (x *qPUAPIGetWriteLogServer) Send(m *qpuextapi.WriteLogOp) error {
	return x.ServerStream.SendMsg(m)
}

func _QPUAPI_LobstersFrontpage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(qpuextapi.LobFrontpageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QPUAPIServer).LobstersFrontpage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qpuapi.QPUAPI/LobstersFrontpage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QPUAPIServer).LobstersFrontpage(ctx, req.(*qpuextapi.LobFrontpageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _QPUAPI_LobstersStoryVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(qpuextapi.LobStoryVoteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QPUAPIServer).LobstersStoryVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qpuapi.QPUAPI/LobstersStoryVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QPUAPIServer).LobstersStoryVote(ctx, req.(*qpuextapi.LobStoryVoteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _QPUAPI_LobstersStoryVoteInsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(qpuextapi.LobStoryVoteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QPUAPIServer).LobstersStoryVoteInsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qpuapi.QPUAPI/LobstersStoryVoteInsert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QPUAPIServer).LobstersStoryVoteInsert(ctx, req.(*qpuextapi.LobStoryVoteReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _QPUAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "qpuapi.QPUAPI",
	HandlerType: (*QPUAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryUnary",
			Handler:    _QPUAPI_QueryUnary_Handler,
		},
		{
			MethodName: "QueryUnary1",
			Handler:    _QPUAPI_QueryUnary1_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _QPUAPI_GetConfig_Handler,
		},
		{
			MethodName: "GetMetrics",
			Handler:    _QPUAPI_GetMetrics_Handler,
		},
		{
			MethodName: "LobstersFrontpage",
			Handler:    _QPUAPI_LobstersFrontpage_Handler,
		},
		{
			MethodName: "LobstersStoryVote",
			Handler:    _QPUAPI_LobstersStoryVote_Handler,
		},
		{
			MethodName: "LobstersStoryVoteInsert",
			Handler:    _QPUAPI_LobstersStoryVoteInsert_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Query",
			Handler:       _QPUAPI_Query_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "GetWriteLog",
			Handler:       _QPUAPI_GetWriteLog_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/protobuf-spec/qpuapi.proto",
}
