version: '3'
services:
  client-0:
    image: dvasilas/ycsb:${YCSB_IMAGE_TAG}
    volumes:
      - ${OUTDIR}:/ycsb
    networks:
      - proteus_net
    environment:
      - TYPE=run
      - TABLE=ycsb-buck
      - USEBARRIER=true
      - SLEEP=125
      - S3HOST=cloudserver-0
      - S3PORT=8000
      - S3ACCESSKEYID=accessKey1
      - S3SECRETKEY=verySecretKey1
      - WORKLOAD=workloada
      - PROTEUSHOST=federation-0
      - PROTEUSPORT=50450
      - RECORDCOUNT=${RECORDCOUNT}
      - INSERTSTART=${INSERTSTART0}
      - QUERYPROPORTION=${QUERYPROPORTION}
      - UPDATEPROPORTION=${UPDATEPROPORTION}
      - CACHEDQUERYPROPORTION=${CACHEDQUERYPROPORTION}
      - EXECUTIONTIME=120
      - WARMUPTIME=20
      - THREADS=${THREADS}
      - OUTPUT_FILE_NAME=${OUTPUT_FILE_NAME}_c0
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints: [ node.labels.dc0_node0 == true ]

  client-1:
    image: dvasilas/ycsb:${YCSB_IMAGE_TAG}
    volumes:
      - ${OUTDIR}:/ycsb
    networks:
      - proteus_net
    environment:
      - TYPE=run
      - TABLE=ycsb-buck
      - USEBARRIER=true
      - SLEEP=140
      - S3HOST=cloudserver-1
      - S3PORT=8000
      - S3ACCESSKEYID=accessKey1
      - S3SECRETKEY=verySecretKey1
      - WORKLOAD=workloada
      - PROTEUSHOST=federation-1
      - PROTEUSPORT=50450
      - RECORDCOUNT=${RECORDCOUNT}
      - INSERTSTART=${INSERTSTART1}
      - QUERYPROPORTION=${QUERYPROPORTION}
      - UPDATEPROPORTION=${UPDATEPROPORTION}
      - CACHEDQUERYPROPORTION=${CACHEDQUERYPROPORTION}
      - EXECUTIONTIME=120
      - WARMUPTIME=20
      - THREADS=${THREADS}
      - OUTPUT_FILE_NAME=${OUTPUT_FILE_NAME}_c1
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints: [ node.labels.dc1_node0 == true ]

  client-2:
    image: dvasilas/ycsb:${YCSB_IMAGE_TAG}
    volumes:
      - ${OUTDIR}:/ycsb
    networks:
      - proteus_net
    environment:
      - TYPE=run
      - TABLE=ycsb-buck
      - USEBARRIER=true
      - S3HOST=cloudserver-2
      - S3PORT=8000
      - S3ACCESSKEYID=accessKey1
      - S3SECRETKEY=verySecretKey1
      - WORKLOAD=workloada
      - PROTEUSHOST=federation-2
      - PROTEUSPORT=50450
      - RECORDCOUNT=${RECORDCOUNT}
      - INSERTSTART=${INSERTSTART2}
      - QUERYPROPORTION=${QUERYPROPORTION}
      - UPDATEPROPORTION=${UPDATEPROPORTION}
      - CACHEDQUERYPROPORTION=${CACHEDQUERYPROPORTION}
      - EXECUTIONTIME=120
      - WARMUPTIME=20
      - THREADS=${THREADS}
      - OUTPUT_FILE_NAME=${OUTPUT_FILE_NAME}_c2
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints: [ node.labels.dc2_node0 == true ]

networks:
  proteus_net:
    external: true
