// Code generated by protoc-gen-go. DO NOT EDIT.
// source: s3.proto

package s3

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NotificationStream_StreamRecordType int32

const (
	NotificationStream_UpdateDelta NotificationStream_StreamRecordType = 0
)

var NotificationStream_StreamRecordType_name = map[int32]string{
	0: "UpdateDelta",
}

var NotificationStream_StreamRecordType_value = map[string]int32{
	"UpdateDelta": 0,
}

func (x NotificationStream_StreamRecordType) String() string {
	return proto.EnumName(NotificationStream_StreamRecordType_name, int32(x))
}

func (NotificationStream_StreamRecordType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_005e34be4304e022, []int{0, 0}
}

type NotificationStream struct {
	SequenceId           int64                               `protobuf:"varint,1,opt,name=sequence_id,json=sequenceId,proto3" json:"sequence_id,omitempty"`
	Type                 NotificationStream_StreamRecordType `protobuf:"varint,2,opt,name=type,proto3,enum=notificationpubsub.NotificationStream_StreamRecordType" json:"type,omitempty"`
	Payload              *Payload                            `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Timestamp            int64                               `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *NotificationStream) Reset()         { *m = NotificationStream{} }
func (m *NotificationStream) String() string { return proto.CompactTextString(m) }
func (*NotificationStream) ProtoMessage()    {}
func (*NotificationStream) Descriptor() ([]byte, []int) {
	return fileDescriptor_005e34be4304e022, []int{0}
}

func (m *NotificationStream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotificationStream.Unmarshal(m, b)
}
func (m *NotificationStream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotificationStream.Marshal(b, m, deterministic)
}
func (m *NotificationStream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotificationStream.Merge(m, src)
}
func (m *NotificationStream) XXX_Size() int {
	return xxx_messageInfo_NotificationStream.Size(m)
}
func (m *NotificationStream) XXX_DiscardUnknown() {
	xxx_messageInfo_NotificationStream.DiscardUnknown(m)
}

var xxx_messageInfo_NotificationStream proto.InternalMessageInfo

func (m *NotificationStream) GetSequenceId() int64 {
	if m != nil {
		return m.SequenceId
	}
	return 0
}

func (m *NotificationStream) GetType() NotificationStream_StreamRecordType {
	if m != nil {
		return m.Type
	}
	return NotificationStream_UpdateDelta
}

func (m *NotificationStream) GetPayload() *Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *NotificationStream) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type Payload struct {
	ObjectId             string               `protobuf:"bytes,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	Bucket               string               `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	OldState             *Payload_ObjectState `protobuf:"bytes,3,opt,name=old_state,json=oldState,proto3" json:"old_state,omitempty"`
	NewState             *Payload_ObjectState `protobuf:"bytes,4,opt,name=new_state,json=newState,proto3" json:"new_state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Payload) Reset()         { *m = Payload{} }
func (m *Payload) String() string { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()    {}
func (*Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_005e34be4304e022, []int{1}
}

func (m *Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload.Unmarshal(m, b)
}
func (m *Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload.Marshal(b, m, deterministic)
}
func (m *Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload.Merge(m, src)
}
func (m *Payload) XXX_Size() int {
	return xxx_messageInfo_Payload.Size(m)
}
func (m *Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_Payload proto.InternalMessageInfo

func (m *Payload) GetObjectId() string {
	if m != nil {
		return m.ObjectId
	}
	return ""
}

func (m *Payload) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *Payload) GetOldState() *Payload_ObjectState {
	if m != nil {
		return m.OldState
	}
	return nil
}

func (m *Payload) GetNewState() *Payload_ObjectState {
	if m != nil {
		return m.NewState
	}
	return nil
}

type Payload_ObjectState struct {
	ContentLength        int64             `protobuf:"varint,1,opt,name=contentLength,proto3" json:"contentLength,omitempty"`
	LastModified         int64             `protobuf:"varint,2,opt,name=lastModified,proto3" json:"lastModified,omitempty"`
	Attributes           map[string]string `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Payload_ObjectState) Reset()         { *m = Payload_ObjectState{} }
func (m *Payload_ObjectState) String() string { return proto.CompactTextString(m) }
func (*Payload_ObjectState) ProtoMessage()    {}
func (*Payload_ObjectState) Descriptor() ([]byte, []int) {
	return fileDescriptor_005e34be4304e022, []int{1, 0}
}

func (m *Payload_ObjectState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload_ObjectState.Unmarshal(m, b)
}
func (m *Payload_ObjectState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload_ObjectState.Marshal(b, m, deterministic)
}
func (m *Payload_ObjectState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload_ObjectState.Merge(m, src)
}
func (m *Payload_ObjectState) XXX_Size() int {
	return xxx_messageInfo_Payload_ObjectState.Size(m)
}
func (m *Payload_ObjectState) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload_ObjectState.DiscardUnknown(m)
}

var xxx_messageInfo_Payload_ObjectState proto.InternalMessageInfo

func (m *Payload_ObjectState) GetContentLength() int64 {
	if m != nil {
		return m.ContentLength
	}
	return 0
}

func (m *Payload_ObjectState) GetLastModified() int64 {
	if m != nil {
		return m.LastModified
	}
	return 0
}

func (m *Payload_ObjectState) GetAttributes() map[string]string {
	if m != nil {
		return m.Attributes
	}
	return nil
}

type RequestStream struct {
	// Types that are valid to be assigned to Val:
	//	*RequestStream_Request
	//	*RequestStream_Ack
	Val                  isRequestStream_Val `protobuf_oneof:"val"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *RequestStream) Reset()         { *m = RequestStream{} }
func (m *RequestStream) String() string { return proto.CompactTextString(m) }
func (*RequestStream) ProtoMessage()    {}
func (*RequestStream) Descriptor() ([]byte, []int) {
	return fileDescriptor_005e34be4304e022, []int{2}
}

func (m *RequestStream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestStream.Unmarshal(m, b)
}
func (m *RequestStream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestStream.Marshal(b, m, deterministic)
}
func (m *RequestStream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestStream.Merge(m, src)
}
func (m *RequestStream) XXX_Size() int {
	return xxx_messageInfo_RequestStream.Size(m)
}
func (m *RequestStream) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestStream.DiscardUnknown(m)
}

var xxx_messageInfo_RequestStream proto.InternalMessageInfo

type isRequestStream_Val interface {
	isRequestStream_Val()
}

type RequestStream_Request struct {
	Request *SubRequest `protobuf:"bytes,1,opt,name=request,proto3,oneof"`
}

type RequestStream_Ack struct {
	Ack *AckMsg `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

func (*RequestStream_Request) isRequestStream_Val() {}

func (*RequestStream_Ack) isRequestStream_Val() {}

func (m *RequestStream) GetVal() isRequestStream_Val {
	if m != nil {
		return m.Val
	}
	return nil
}

func (m *RequestStream) GetRequest() *SubRequest {
	if x, ok := m.GetVal().(*RequestStream_Request); ok {
		return x.Request
	}
	return nil
}

func (m *RequestStream) GetAck() *AckMsg {
	if x, ok := m.GetVal().(*RequestStream_Ack); ok {
		return x.Ack
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*RequestStream) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*RequestStream_Request)(nil),
		(*RequestStream_Ack)(nil),
	}
}

type SubRequest struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Sync                 bool     `protobuf:"varint,2,opt,name=sync,proto3" json:"sync,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubRequest) Reset()         { *m = SubRequest{} }
func (m *SubRequest) String() string { return proto.CompactTextString(m) }
func (*SubRequest) ProtoMessage()    {}
func (*SubRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_005e34be4304e022, []int{3}
}

func (m *SubRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubRequest.Unmarshal(m, b)
}
func (m *SubRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubRequest.Marshal(b, m, deterministic)
}
func (m *SubRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubRequest.Merge(m, src)
}
func (m *SubRequest) XXX_Size() int {
	return xxx_messageInfo_SubRequest.Size(m)
}
func (m *SubRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubRequest proto.InternalMessageInfo

func (m *SubRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *SubRequest) GetSync() bool {
	if m != nil {
		return m.Sync
	}
	return false
}

type AckMsg struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AckMsg) Reset()         { *m = AckMsg{} }
func (m *AckMsg) String() string { return proto.CompactTextString(m) }
func (*AckMsg) ProtoMessage()    {}
func (*AckMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_005e34be4304e022, []int{4}
}

func (m *AckMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckMsg.Unmarshal(m, b)
}
func (m *AckMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckMsg.Marshal(b, m, deterministic)
}
func (m *AckMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckMsg.Merge(m, src)
}
func (m *AckMsg) XXX_Size() int {
	return xxx_messageInfo_AckMsg.Size(m)
}
func (m *AckMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_AckMsg.DiscardUnknown(m)
}

var xxx_messageInfo_AckMsg proto.InternalMessageInfo

func (m *AckMsg) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func init() {
	proto.RegisterEnum("notificationpubsub.NotificationStream_StreamRecordType", NotificationStream_StreamRecordType_name, NotificationStream_StreamRecordType_value)
	proto.RegisterType((*NotificationStream)(nil), "notificationpubsub.NotificationStream")
	proto.RegisterType((*Payload)(nil), "notificationpubsub.Payload")
	proto.RegisterType((*Payload_ObjectState)(nil), "notificationpubsub.Payload.ObjectState")
	proto.RegisterMapType((map[string]string)(nil), "notificationpubsub.Payload.ObjectState.AttributesEntry")
	proto.RegisterType((*RequestStream)(nil), "notificationpubsub.RequestStream")
	proto.RegisterType((*SubRequest)(nil), "notificationpubsub.SubRequest")
	proto.RegisterType((*AckMsg)(nil), "notificationpubsub.AckMsg")
}

func init() { proto.RegisterFile("s3.proto", fileDescriptor_005e34be4304e022) }

var fileDescriptor_005e34be4304e022 = []byte{
	// 561 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0x51, 0x6b, 0xd4, 0x40,
	0x10, 0xc7, 0x6f, 0x9b, 0x6b, 0x7b, 0x37, 0xb1, 0xb6, 0xac, 0x52, 0x8e, 0xab, 0xe8, 0x19, 0xa5,
	0x9e, 0x08, 0x39, 0xb9, 0x22, 0x4a, 0x41, 0xa1, 0xa5, 0x42, 0x8b, 0x56, 0x65, 0xab, 0x08, 0xbe,
	0x94, 0xcd, 0x66, 0xda, 0xae, 0x97, 0xcb, 0xc6, 0xec, 0xe6, 0x4a, 0xde, 0xc4, 0xcf, 0xe5, 0x77,
	0xf2, 0x0b, 0xf8, 0x20, 0xd9, 0xe4, 0xec, 0x5d, 0x1b, 0x8a, 0x3e, 0x65, 0xf6, 0xbf, 0x33, 0xbf,
	0x9d, 0xd9, 0x99, 0x0d, 0xb4, 0xf4, 0x96, 0x9f, 0xa4, 0xca, 0x28, 0x4a, 0x63, 0x65, 0xe4, 0x89,
	0x14, 0xdc, 0x48, 0x15, 0x27, 0x59, 0xa0, 0xb3, 0xc0, 0xfb, 0x4d, 0x80, 0xbe, 0x9b, 0x91, 0x8f,
	0x4c, 0x8a, 0x7c, 0x4c, 0xef, 0x81, 0xab, 0xf1, 0x5b, 0x86, 0xb1, 0xc0, 0x63, 0x19, 0x76, 0x48,
	0x8f, 0xf4, 0x1d, 0x06, 0x53, 0xe9, 0x20, 0xa4, 0x6f, 0xa0, 0x69, 0xf2, 0x04, 0x3b, 0x0b, 0x3d,
	0xd2, 0xbf, 0x39, 0x7c, 0xee, 0x5f, 0x45, 0xfb, 0x57, 0xb1, 0x7e, 0xf9, 0x61, 0x28, 0x54, 0x1a,
	0x7e, 0xcc, 0x13, 0x64, 0x16, 0x42, 0x9f, 0xc1, 0x72, 0xc2, 0xf3, 0x48, 0xf1, 0xb0, 0xe3, 0xf4,
	0x48, 0xdf, 0x1d, 0x6e, 0xd4, 0xf1, 0x3e, 0x94, 0x2e, 0x6c, 0xea, 0x4b, 0xef, 0x40, 0xdb, 0xc8,
	0x31, 0x6a, 0xc3, 0xc7, 0x49, 0xa7, 0x69, 0x53, 0xbc, 0x10, 0xbc, 0x07, 0xb0, 0x76, 0xf9, 0x38,
	0xba, 0x0a, 0xee, 0xa7, 0x24, 0xe4, 0x06, 0xf7, 0x30, 0x32, 0x7c, 0xad, 0xe1, 0xfd, 0x74, 0x60,
	0xb9, 0xe2, 0xd2, 0x0d, 0x68, 0xab, 0xe0, 0x2b, 0x0a, 0x33, 0xad, 0xb8, 0xcd, 0x5a, 0xa5, 0x70,
	0x10, 0xd2, 0x75, 0x58, 0x0a, 0x32, 0x31, 0x42, 0x63, 0x2b, 0x6e, 0xb3, 0x6a, 0x45, 0xf7, 0xa0,
	0xad, 0xa2, 0xf0, 0x58, 0x1b, 0x6e, 0xb0, 0x4a, 0xfe, 0xd1, 0x35, 0xc9, 0xfb, 0xef, 0x2d, 0xf0,
	0xa8, 0x70, 0x67, 0x2d, 0x15, 0x85, 0xd6, 0x2a, 0x28, 0x31, 0x9e, 0x57, 0x94, 0xe6, 0x7f, 0x52,
	0x62, 0x3c, 0xb7, 0x56, 0xf7, 0x17, 0x01, 0x77, 0x66, 0x87, 0x3e, 0x84, 0x15, 0xa1, 0x62, 0x83,
	0xb1, 0x79, 0x8b, 0xf1, 0xa9, 0x39, 0xab, 0xda, 0x38, 0x2f, 0x52, 0x0f, 0x6e, 0x44, 0x5c, 0x9b,
	0x43, 0x15, 0xca, 0x13, 0x89, 0xa1, 0xad, 0xcf, 0x61, 0x73, 0x1a, 0xfd, 0x0c, 0xc0, 0x8d, 0x49,
	0x65, 0x90, 0x19, 0xd4, 0x1d, 0xa7, 0xe7, 0xf4, 0xdd, 0xfa, 0x9e, 0xd7, 0x24, 0xe8, 0xef, 0xfc,
	0x8d, 0x7c, 0x1d, 0x9b, 0x34, 0x67, 0x33, 0xa8, 0xee, 0x4b, 0x58, 0xbd, 0xb4, 0x4d, 0xd7, 0xc0,
	0x19, 0x61, 0x5e, 0x35, 0xa0, 0x30, 0xe9, 0x6d, 0x58, 0x9c, 0xf0, 0x28, 0xc3, 0xea, 0xea, 0xcb,
	0xc5, 0xf6, 0xc2, 0x0b, 0xe2, 0xfd, 0x20, 0xb0, 0xc2, 0x8a, 0xa1, 0xd4, 0xa6, 0x1a, 0xdc, 0x6d,
	0x58, 0x4e, 0x4b, 0xc1, 0x12, 0xdc, 0xe1, 0xdd, 0xba, 0x34, 0x8f, 0xb2, 0xa0, 0x0a, 0xdb, 0x6f,
	0xb0, 0x69, 0x00, 0xf5, 0xc1, 0xe1, 0x62, 0x64, 0x4f, 0x71, 0x87, 0xdd, 0xba, 0xb8, 0x1d, 0x31,
	0x3a, 0xd4, 0xa7, 0xfb, 0x0d, 0x56, 0x38, 0xee, 0x2e, 0x82, 0x33, 0xe1, 0x91, 0xf7, 0x0a, 0xe0,
	0x82, 0x37, 0x3f, 0x94, 0xe4, 0xd2, 0x50, 0x52, 0x0a, 0x4d, 0x9d, 0xc7, 0xc2, 0x9e, 0xd1, 0x62,
	0xd6, 0xf6, 0x36, 0x61, 0xa9, 0xe4, 0x5e, 0x1f, 0x3b, 0xfc, 0x4e, 0xe0, 0xd6, 0xdc, 0x9b, 0xc2,
	0x74, 0x22, 0x05, 0x52, 0x09, 0xeb, 0x3a, 0x0b, 0xb4, 0x48, 0x65, 0x80, 0xb3, 0xfb, 0x9a, 0xde,
	0xaf, 0xab, 0x61, 0xee, 0xbe, 0xba, 0x9b, 0xff, 0xf6, 0x72, 0xbd, 0x46, 0x9f, 0x3c, 0x25, 0xbb,
	0x4f, 0xbe, 0x3c, 0x3e, 0x95, 0xe6, 0x2c, 0x0b, 0x7c, 0xa1, 0xc6, 0x83, 0x70, 0xc2, 0xb5, 0x8c,
	0xb8, 0x1e, 0x14, 0xbf, 0x17, 0xcc, 0xf4, 0x40, 0xa7, 0xc2, 0xda, 0x4a, 0x0f, 0xf4, 0x56, 0xb0,
	0x64, 0xcd, 0xad, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x5f, 0x1f, 0xc6, 0xf5, 0x81, 0x04, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NotificationServiceClient is the client API for NotificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NotificationServiceClient interface {
	SubscribeNotifications(ctx context.Context, opts ...grpc.CallOption) (NotificationService_SubscribeNotificationsClient, error)
}

type notificationServiceClient struct {
	cc *grpc.ClientConn
}

func NewNotificationServiceClient(cc *grpc.ClientConn) NotificationServiceClient {
	return &notificationServiceClient{cc}
}

func (c *notificationServiceClient) SubscribeNotifications(ctx context.Context, opts ...grpc.CallOption) (NotificationService_SubscribeNotificationsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_NotificationService_serviceDesc.Streams[0], "/notificationpubsub.NotificationService/subscribeNotifications", opts...)
	if err != nil {
		return nil, err
	}
	x := &notificationServiceSubscribeNotificationsClient{stream}
	return x, nil
}

type NotificationService_SubscribeNotificationsClient interface {
	Send(*RequestStream) error
	Recv() (*NotificationStream, error)
	grpc.ClientStream
}

type notificationServiceSubscribeNotificationsClient struct {
	grpc.ClientStream
}

func (x *notificationServiceSubscribeNotificationsClient) Send(m *RequestStream) error {
	return x.ClientStream.SendMsg(m)
}

func (x *notificationServiceSubscribeNotificationsClient) Recv() (*NotificationStream, error) {
	m := new(NotificationStream)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NotificationServiceServer is the server API for NotificationService service.
type NotificationServiceServer interface {
	SubscribeNotifications(NotificationService_SubscribeNotificationsServer) error
}

func RegisterNotificationServiceServer(s *grpc.Server, srv NotificationServiceServer) {
	s.RegisterService(&_NotificationService_serviceDesc, srv)
}

func _NotificationService_SubscribeNotifications_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NotificationServiceServer).SubscribeNotifications(&notificationServiceSubscribeNotificationsServer{stream})
}

type NotificationService_SubscribeNotificationsServer interface {
	Send(*NotificationStream) error
	Recv() (*RequestStream, error)
	grpc.ServerStream
}

type notificationServiceSubscribeNotificationsServer struct {
	grpc.ServerStream
}

func (x *notificationServiceSubscribeNotificationsServer) Send(m *NotificationStream) error {
	return x.ServerStream.SendMsg(m)
}

func (x *notificationServiceSubscribeNotificationsServer) Recv() (*RequestStream, error) {
	m := new(RequestStream)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _NotificationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "notificationpubsub.NotificationService",
	HandlerType: (*NotificationServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "subscribeNotifications",
			Handler:       _NotificationService_SubscribeNotifications_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "s3.proto",
}
