// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/protobuf-spec/qpu_api.proto

package qpu_api

import (
	context "context"
	fmt "fmt"
	qpu "github.com/dvasilas/proteus/internal/proto/qpu"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResponseStreamRecord_StreamRecordType int32

const (
	ResponseStreamRecord_UPDATEOP      ResponseStreamRecord_StreamRecordType = 0
	ResponseStreamRecord_UPDATEDELTA   ResponseStreamRecord_StreamRecordType = 1
	ResponseStreamRecord_STATE         ResponseStreamRecord_StreamRecordType = 2
	ResponseStreamRecord_HEARTBEAT     ResponseStreamRecord_StreamRecordType = 3
	ResponseStreamRecord_END_OF_STREAM ResponseStreamRecord_StreamRecordType = 4
)

var ResponseStreamRecord_StreamRecordType_name = map[int32]string{
	0: "UPDATEOP",
	1: "UPDATEDELTA",
	2: "STATE",
	3: "HEARTBEAT",
	4: "END_OF_STREAM",
}

var ResponseStreamRecord_StreamRecordType_value = map[string]int32{
	"UPDATEOP":      0,
	"UPDATEDELTA":   1,
	"STATE":         2,
	"HEARTBEAT":     3,
	"END_OF_STREAM": 4,
}

func (x ResponseStreamRecord_StreamRecordType) String() string {
	return proto.EnumName(ResponseStreamRecord_StreamRecordType_name, int32(x))
}

func (ResponseStreamRecord_StreamRecordType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_55c136aa8978e5e9, []int{3, 0}
}

type ConfigResponse_QPUType int32

const (
	ConfigResponse_DATASTORE_DRIVER ConfigResponse_QPUType = 0
	ConfigResponse_SUM              ConfigResponse_QPUType = 1
	ConfigResponse_JOIN             ConfigResponse_QPUType = 2
)

var ConfigResponse_QPUType_name = map[int32]string{
	0: "DATASTORE_DRIVER",
	1: "SUM",
	2: "JOIN",
}

var ConfigResponse_QPUType_value = map[string]int32{
	"DATASTORE_DRIVER": 0,
	"SUM":              1,
	"JOIN":             2,
}

func (x ConfigResponse_QPUType) String() string {
	return proto.EnumName(ConfigResponse_QPUType_name, int32(x))
}

func (ConfigResponse_QPUType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_55c136aa8978e5e9, []int{8, 0}
}

type GetDataRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDataRequest) Reset()         { *m = GetDataRequest{} }
func (m *GetDataRequest) String() string { return proto.CompactTextString(m) }
func (*GetDataRequest) ProtoMessage()    {}
func (*GetDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_55c136aa8978e5e9, []int{0}
}

func (m *GetDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataRequest.Unmarshal(m, b)
}
func (m *GetDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataRequest.Marshal(b, m, deterministic)
}
func (m *GetDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataRequest.Merge(m, src)
}
func (m *GetDataRequest) XXX_Size() int {
	return xxx_messageInfo_GetDataRequest.Size(m)
}
func (m *GetDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataRequest proto.InternalMessageInfo

type DataTransferResponse struct {
	KBytesTranferred     float32  `protobuf:"fixed32,1,opt,name=kBytesTranferred,proto3" json:"kBytesTranferred,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataTransferResponse) Reset()         { *m = DataTransferResponse{} }
func (m *DataTransferResponse) String() string { return proto.CompactTextString(m) }
func (*DataTransferResponse) ProtoMessage()    {}
func (*DataTransferResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_55c136aa8978e5e9, []int{1}
}

func (m *DataTransferResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataTransferResponse.Unmarshal(m, b)
}
func (m *DataTransferResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataTransferResponse.Marshal(b, m, deterministic)
}
func (m *DataTransferResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataTransferResponse.Merge(m, src)
}
func (m *DataTransferResponse) XXX_Size() int {
	return xxx_messageInfo_DataTransferResponse.Size(m)
}
func (m *DataTransferResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DataTransferResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DataTransferResponse proto.InternalMessageInfo

func (m *DataTransferResponse) GetKBytesTranferred() float32 {
	if m != nil {
		return m.KBytesTranferred
	}
	return 0
}

type RequestStreamRecord struct {
	// Types that are valid to be assigned to Request:
	//	*RequestStreamRecord_QueryRequest
	//	*RequestStreamRecord_Ack
	//	*RequestStreamRecord_Ping
	Request              isRequestStreamRecord_Request `protobuf_oneof:"request"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *RequestStreamRecord) Reset()         { *m = RequestStreamRecord{} }
func (m *RequestStreamRecord) String() string { return proto.CompactTextString(m) }
func (*RequestStreamRecord) ProtoMessage()    {}
func (*RequestStreamRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_55c136aa8978e5e9, []int{2}
}

func (m *RequestStreamRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestStreamRecord.Unmarshal(m, b)
}
func (m *RequestStreamRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestStreamRecord.Marshal(b, m, deterministic)
}
func (m *RequestStreamRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestStreamRecord.Merge(m, src)
}
func (m *RequestStreamRecord) XXX_Size() int {
	return xxx_messageInfo_RequestStreamRecord.Size(m)
}
func (m *RequestStreamRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestStreamRecord.DiscardUnknown(m)
}

var xxx_messageInfo_RequestStreamRecord proto.InternalMessageInfo

type isRequestStreamRecord_Request interface {
	isRequestStreamRecord_Request()
}

type RequestStreamRecord_QueryRequest struct {
	QueryRequest *QueryRequest `protobuf:"bytes,1,opt,name=queryRequest,proto3,oneof"`
}

type RequestStreamRecord_Ack struct {
	Ack *AckMsg `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

type RequestStreamRecord_Ping struct {
	Ping *PingMsg `protobuf:"bytes,3,opt,name=ping,proto3,oneof"`
}

func (*RequestStreamRecord_QueryRequest) isRequestStreamRecord_Request() {}

func (*RequestStreamRecord_Ack) isRequestStreamRecord_Request() {}

func (*RequestStreamRecord_Ping) isRequestStreamRecord_Request() {}

func (m *RequestStreamRecord) GetRequest() isRequestStreamRecord_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *RequestStreamRecord) GetQueryRequest() *QueryRequest {
	if x, ok := m.GetRequest().(*RequestStreamRecord_QueryRequest); ok {
		return x.QueryRequest
	}
	return nil
}

func (m *RequestStreamRecord) GetAck() *AckMsg {
	if x, ok := m.GetRequest().(*RequestStreamRecord_Ack); ok {
		return x.Ack
	}
	return nil
}

func (m *RequestStreamRecord) GetPing() *PingMsg {
	if x, ok := m.GetRequest().(*RequestStreamRecord_Ping); ok {
		return x.Ping
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*RequestStreamRecord) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*RequestStreamRecord_QueryRequest)(nil),
		(*RequestStreamRecord_Ack)(nil),
		(*RequestStreamRecord_Ping)(nil),
	}
}

type ResponseStreamRecord struct {
	SequenceId           int64                                 `protobuf:"varint,1,opt,name=sequence_id,json=sequenceId,proto3" json:"sequence_id,omitempty"`
	Type                 ResponseStreamRecord_StreamRecordType `protobuf:"varint,2,opt,name=type,proto3,enum=ResponseStreamRecord_StreamRecordType" json:"type,omitempty"`
	LogOp                *qpu.LogOperation                     `protobuf:"bytes,3,opt,name=logOp,proto3" json:"logOp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *ResponseStreamRecord) Reset()         { *m = ResponseStreamRecord{} }
func (m *ResponseStreamRecord) String() string { return proto.CompactTextString(m) }
func (*ResponseStreamRecord) ProtoMessage()    {}
func (*ResponseStreamRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_55c136aa8978e5e9, []int{3}
}

func (m *ResponseStreamRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseStreamRecord.Unmarshal(m, b)
}
func (m *ResponseStreamRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseStreamRecord.Marshal(b, m, deterministic)
}
func (m *ResponseStreamRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseStreamRecord.Merge(m, src)
}
func (m *ResponseStreamRecord) XXX_Size() int {
	return xxx_messageInfo_ResponseStreamRecord.Size(m)
}
func (m *ResponseStreamRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseStreamRecord.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseStreamRecord proto.InternalMessageInfo

func (m *ResponseStreamRecord) GetSequenceId() int64 {
	if m != nil {
		return m.SequenceId
	}
	return 0
}

func (m *ResponseStreamRecord) GetType() ResponseStreamRecord_StreamRecordType {
	if m != nil {
		return m.Type
	}
	return ResponseStreamRecord_UPDATEOP
}

func (m *ResponseStreamRecord) GetLogOp() *qpu.LogOperation {
	if m != nil {
		return m.LogOp
	}
	return nil
}

type QueryRequest struct {
	Query                *Query            `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Sync                 bool              `protobuf:"varint,3,opt,name=sync,proto3" json:"sync,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *QueryRequest) Reset()         { *m = QueryRequest{} }
func (m *QueryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()    {}
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_55c136aa8978e5e9, []int{4}
}

func (m *QueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRequest.Unmarshal(m, b)
}
func (m *QueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRequest.Marshal(b, m, deterministic)
}
func (m *QueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRequest.Merge(m, src)
}
func (m *QueryRequest) XXX_Size() int {
	return xxx_messageInfo_QueryRequest.Size(m)
}
func (m *QueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRequest proto.InternalMessageInfo

func (m *QueryRequest) GetQuery() *Query {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *QueryRequest) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *QueryRequest) GetSync() bool {
	if m != nil {
		return m.Sync
	}
	return false
}

type Query struct {
	// Types that are valid to be assigned to Val:
	//	*Query_QueryI
	//	*Query_QuerySql
	Val                  isQuery_Val `protobuf_oneof:"val"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Query) Reset()         { *m = Query{} }
func (m *Query) String() string { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()    {}
func (*Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_55c136aa8978e5e9, []int{5}
}

func (m *Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Query.Unmarshal(m, b)
}
func (m *Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Query.Marshal(b, m, deterministic)
}
func (m *Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Query.Merge(m, src)
}
func (m *Query) XXX_Size() int {
	return xxx_messageInfo_Query.Size(m)
}
func (m *Query) XXX_DiscardUnknown() {
	xxx_messageInfo_Query.DiscardUnknown(m)
}

var xxx_messageInfo_Query proto.InternalMessageInfo

type isQuery_Val interface {
	isQuery_Val()
}

type Query_QueryI struct {
	QueryI *QueryInternalQuery `protobuf:"bytes,1,opt,name=query_i,json=queryI,proto3,oneof"`
}

type Query_QuerySql struct {
	QuerySql *Query_SQLQuery `protobuf:"bytes,2,opt,name=query_sql,json=querySql,proto3,oneof"`
}

func (*Query_QueryI) isQuery_Val() {}

func (*Query_QuerySql) isQuery_Val() {}

func (m *Query) GetVal() isQuery_Val {
	if m != nil {
		return m.Val
	}
	return nil
}

func (m *Query) GetQueryI() *QueryInternalQuery {
	if x, ok := m.GetVal().(*Query_QueryI); ok {
		return x.QueryI
	}
	return nil
}

func (m *Query) GetQuerySql() *Query_SQLQuery {
	if x, ok := m.GetVal().(*Query_QuerySql); ok {
		return x.QuerySql
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Query) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Query_QueryI)(nil),
		(*Query_QuerySql)(nil),
	}
}

type QueryInternalQuery struct {
	Table                string                     `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Projection           []string                   `protobuf:"bytes,2,rep,name=projection,proto3" json:"projection,omitempty"`
	Predicate            []*qpu.AttributePredicate  `protobuf:"bytes,3,rep,name=predicate,proto3" json:"predicate,omitempty"`
	TsPredicate          *qpu.SnapshotTimePredicate `protobuf:"bytes,4,opt,name=tsPredicate,proto3" json:"tsPredicate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *QueryInternalQuery) Reset()         { *m = QueryInternalQuery{} }
func (m *QueryInternalQuery) String() string { return proto.CompactTextString(m) }
func (*QueryInternalQuery) ProtoMessage()    {}
func (*QueryInternalQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_55c136aa8978e5e9, []int{5, 0}
}

func (m *QueryInternalQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryInternalQuery.Unmarshal(m, b)
}
func (m *QueryInternalQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryInternalQuery.Marshal(b, m, deterministic)
}
func (m *QueryInternalQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryInternalQuery.Merge(m, src)
}
func (m *QueryInternalQuery) XXX_Size() int {
	return xxx_messageInfo_QueryInternalQuery.Size(m)
}
func (m *QueryInternalQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryInternalQuery.DiscardUnknown(m)
}

var xxx_messageInfo_QueryInternalQuery proto.InternalMessageInfo

func (m *QueryInternalQuery) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *QueryInternalQuery) GetProjection() []string {
	if m != nil {
		return m.Projection
	}
	return nil
}

func (m *QueryInternalQuery) GetPredicate() []*qpu.AttributePredicate {
	if m != nil {
		return m.Predicate
	}
	return nil
}

func (m *QueryInternalQuery) GetTsPredicate() *qpu.SnapshotTimePredicate {
	if m != nil {
		return m.TsPredicate
	}
	return nil
}

type Query_SQLQuery struct {
	QueryStr             string   `protobuf:"bytes,1,opt,name=queryStr,proto3" json:"queryStr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Query_SQLQuery) Reset()         { *m = Query_SQLQuery{} }
func (m *Query_SQLQuery) String() string { return proto.CompactTextString(m) }
func (*Query_SQLQuery) ProtoMessage()    {}
func (*Query_SQLQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_55c136aa8978e5e9, []int{5, 1}
}

func (m *Query_SQLQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Query_SQLQuery.Unmarshal(m, b)
}
func (m *Query_SQLQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Query_SQLQuery.Marshal(b, m, deterministic)
}
func (m *Query_SQLQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Query_SQLQuery.Merge(m, src)
}
func (m *Query_SQLQuery) XXX_Size() int {
	return xxx_messageInfo_Query_SQLQuery.Size(m)
}
func (m *Query_SQLQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_Query_SQLQuery.DiscardUnknown(m)
}

var xxx_messageInfo_Query_SQLQuery proto.InternalMessageInfo

func (m *Query_SQLQuery) GetQueryStr() string {
	if m != nil {
		return m.QueryStr
	}
	return ""
}

type AckMsg struct {
	SequenceId           int64    `protobuf:"varint,1,opt,name=sequence_id,json=sequenceId,proto3" json:"sequence_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AckMsg) Reset()         { *m = AckMsg{} }
func (m *AckMsg) String() string { return proto.CompactTextString(m) }
func (*AckMsg) ProtoMessage()    {}
func (*AckMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_55c136aa8978e5e9, []int{6}
}

func (m *AckMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckMsg.Unmarshal(m, b)
}
func (m *AckMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckMsg.Marshal(b, m, deterministic)
}
func (m *AckMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckMsg.Merge(m, src)
}
func (m *AckMsg) XXX_Size() int {
	return xxx_messageInfo_AckMsg.Size(m)
}
func (m *AckMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_AckMsg.DiscardUnknown(m)
}

var xxx_messageInfo_AckMsg proto.InternalMessageInfo

func (m *AckMsg) GetSequenceId() int64 {
	if m != nil {
		return m.SequenceId
	}
	return 0
}

type ConfigRequest struct {
	Clock                *qpu.SnapshotTimePredicate `protobuf:"bytes,1,opt,name=clock,proto3" json:"clock,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ConfigRequest) Reset()         { *m = ConfigRequest{} }
func (m *ConfigRequest) String() string { return proto.CompactTextString(m) }
func (*ConfigRequest) ProtoMessage()    {}
func (*ConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_55c136aa8978e5e9, []int{7}
}

func (m *ConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigRequest.Unmarshal(m, b)
}
func (m *ConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigRequest.Marshal(b, m, deterministic)
}
func (m *ConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigRequest.Merge(m, src)
}
func (m *ConfigRequest) XXX_Size() int {
	return xxx_messageInfo_ConfigRequest.Size(m)
}
func (m *ConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigRequest proto.InternalMessageInfo

func (m *ConfigRequest) GetClock() *qpu.SnapshotTimePredicate {
	if m != nil {
		return m.Clock
	}
	return nil
}

type ConfigResponse struct {
	QpuType              ConfigResponse_QPUType    `protobuf:"varint,1,opt,name=qpu_type,json=qpuType,proto3,enum=ConfigResponse_QPUType" json:"qpu_type,omitempty"`
	SupportedQueries     []*qpu.AttributePredicate `protobuf:"bytes,2,rep,name=supportedQueries,proto3" json:"supportedQueries,omitempty"`
	Dataset              *DataSet                  `protobuf:"bytes,3,opt,name=dataset,proto3" json:"dataset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ConfigResponse) Reset()         { *m = ConfigResponse{} }
func (m *ConfigResponse) String() string { return proto.CompactTextString(m) }
func (*ConfigResponse) ProtoMessage()    {}
func (*ConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_55c136aa8978e5e9, []int{8}
}

func (m *ConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigResponse.Unmarshal(m, b)
}
func (m *ConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigResponse.Marshal(b, m, deterministic)
}
func (m *ConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigResponse.Merge(m, src)
}
func (m *ConfigResponse) XXX_Size() int {
	return xxx_messageInfo_ConfigResponse.Size(m)
}
func (m *ConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigResponse proto.InternalMessageInfo

func (m *ConfigResponse) GetQpuType() ConfigResponse_QPUType {
	if m != nil {
		return m.QpuType
	}
	return ConfigResponse_DATASTORE_DRIVER
}

func (m *ConfigResponse) GetSupportedQueries() []*qpu.AttributePredicate {
	if m != nil {
		return m.SupportedQueries
	}
	return nil
}

func (m *ConfigResponse) GetDataset() *DataSet {
	if m != nil {
		return m.Dataset
	}
	return nil
}

type DataSet struct {
	Databases            map[string]*DataSet_DB `protobuf:"bytes,1,rep,name=databases,proto3" json:"databases,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *DataSet) Reset()         { *m = DataSet{} }
func (m *DataSet) String() string { return proto.CompactTextString(m) }
func (*DataSet) ProtoMessage()    {}
func (*DataSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_55c136aa8978e5e9, []int{9}
}

func (m *DataSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataSet.Unmarshal(m, b)
}
func (m *DataSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataSet.Marshal(b, m, deterministic)
}
func (m *DataSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataSet.Merge(m, src)
}
func (m *DataSet) XXX_Size() int {
	return xxx_messageInfo_DataSet.Size(m)
}
func (m *DataSet) XXX_DiscardUnknown() {
	xxx_messageInfo_DataSet.DiscardUnknown(m)
}

var xxx_messageInfo_DataSet proto.InternalMessageInfo

func (m *DataSet) GetDatabases() map[string]*DataSet_DB {
	if m != nil {
		return m.Databases
	}
	return nil
}

type DataSet_DB struct {
	Datacenters          map[string]*DataSet_DC `protobuf:"bytes,1,rep,name=datacenters,proto3" json:"datacenters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *DataSet_DB) Reset()         { *m = DataSet_DB{} }
func (m *DataSet_DB) String() string { return proto.CompactTextString(m) }
func (*DataSet_DB) ProtoMessage()    {}
func (*DataSet_DB) Descriptor() ([]byte, []int) {
	return fileDescriptor_55c136aa8978e5e9, []int{9, 0}
}

func (m *DataSet_DB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataSet_DB.Unmarshal(m, b)
}
func (m *DataSet_DB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataSet_DB.Marshal(b, m, deterministic)
}
func (m *DataSet_DB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataSet_DB.Merge(m, src)
}
func (m *DataSet_DB) XXX_Size() int {
	return xxx_messageInfo_DataSet_DB.Size(m)
}
func (m *DataSet_DB) XXX_DiscardUnknown() {
	xxx_messageInfo_DataSet_DB.DiscardUnknown(m)
}

var xxx_messageInfo_DataSet_DB proto.InternalMessageInfo

func (m *DataSet_DB) GetDatacenters() map[string]*DataSet_DC {
	if m != nil {
		return m.Datacenters
	}
	return nil
}

type DataSet_DC struct {
	Shards               []string `protobuf:"bytes,1,rep,name=shards,proto3" json:"shards,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataSet_DC) Reset()         { *m = DataSet_DC{} }
func (m *DataSet_DC) String() string { return proto.CompactTextString(m) }
func (*DataSet_DC) ProtoMessage()    {}
func (*DataSet_DC) Descriptor() ([]byte, []int) {
	return fileDescriptor_55c136aa8978e5e9, []int{9, 1}
}

func (m *DataSet_DC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataSet_DC.Unmarshal(m, b)
}
func (m *DataSet_DC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataSet_DC.Marshal(b, m, deterministic)
}
func (m *DataSet_DC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataSet_DC.Merge(m, src)
}
func (m *DataSet_DC) XXX_Size() int {
	return xxx_messageInfo_DataSet_DC.Size(m)
}
func (m *DataSet_DC) XXX_DiscardUnknown() {
	xxx_messageInfo_DataSet_DC.DiscardUnknown(m)
}

var xxx_messageInfo_DataSet_DC proto.InternalMessageInfo

func (m *DataSet_DC) GetShards() []string {
	if m != nil {
		return m.Shards
	}
	return nil
}

type PingMsg struct {
	SeqId                int64    `protobuf:"varint,1,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingMsg) Reset()         { *m = PingMsg{} }
func (m *PingMsg) String() string { return proto.CompactTextString(m) }
func (*PingMsg) ProtoMessage()    {}
func (*PingMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_55c136aa8978e5e9, []int{10}
}

func (m *PingMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingMsg.Unmarshal(m, b)
}
func (m *PingMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingMsg.Marshal(b, m, deterministic)
}
func (m *PingMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingMsg.Merge(m, src)
}
func (m *PingMsg) XXX_Size() int {
	return xxx_messageInfo_PingMsg.Size(m)
}
func (m *PingMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_PingMsg.DiscardUnknown(m)
}

var xxx_messageInfo_PingMsg proto.InternalMessageInfo

func (m *PingMsg) GetSeqId() int64 {
	if m != nil {
		return m.SeqId
	}
	return 0
}

func init() {
	proto.RegisterEnum("ResponseStreamRecord_StreamRecordType", ResponseStreamRecord_StreamRecordType_name, ResponseStreamRecord_StreamRecordType_value)
	proto.RegisterEnum("ConfigResponse_QPUType", ConfigResponse_QPUType_name, ConfigResponse_QPUType_value)
	proto.RegisterType((*GetDataRequest)(nil), "GetDataRequest")
	proto.RegisterType((*DataTransferResponse)(nil), "DataTransferResponse")
	proto.RegisterType((*RequestStreamRecord)(nil), "RequestStreamRecord")
	proto.RegisterType((*ResponseStreamRecord)(nil), "ResponseStreamRecord")
	proto.RegisterType((*QueryRequest)(nil), "QueryRequest")
	proto.RegisterMapType((map[string]string)(nil), "QueryRequest.MetadataEntry")
	proto.RegisterType((*Query)(nil), "Query")
	proto.RegisterType((*QueryInternalQuery)(nil), "Query.internalQuery")
	proto.RegisterType((*Query_SQLQuery)(nil), "Query.SQLQuery")
	proto.RegisterType((*AckMsg)(nil), "AckMsg")
	proto.RegisterType((*ConfigRequest)(nil), "ConfigRequest")
	proto.RegisterType((*ConfigResponse)(nil), "ConfigResponse")
	proto.RegisterType((*DataSet)(nil), "DataSet")
	proto.RegisterMapType((map[string]*DataSet_DB)(nil), "DataSet.DatabasesEntry")
	proto.RegisterType((*DataSet_DB)(nil), "DataSet.DB")
	proto.RegisterMapType((map[string]*DataSet_DC)(nil), "DataSet.DB.DatacentersEntry")
	proto.RegisterType((*DataSet_DC)(nil), "DataSet.DC")
	proto.RegisterType((*PingMsg)(nil), "PingMsg")
}

func init() { proto.RegisterFile("api/protobuf-spec/qpu_api.proto", fileDescriptor_55c136aa8978e5e9) }

var fileDescriptor_55c136aa8978e5e9 = []byte{
	// 991 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0x8e, 0x9d, 0xff, 0x93, 0xa6, 0xf5, 0x0e, 0x29, 0x1b, 0xb9, 0xd5, 0x6e, 0xf1, 0xc5, 0x52,
	0x90, 0x70, 0x57, 0x59, 0x10, 0xa8, 0x8b, 0x90, 0x9c, 0xc6, 0x6c, 0x03, 0xed, 0x26, 0x9d, 0xb8,
	0x5c, 0x70, 0x41, 0x34, 0x71, 0xa6, 0xa9, 0x49, 0x6a, 0x3b, 0x9e, 0x71, 0xa5, 0x3c, 0x06, 0xbc,
	0x09, 0x37, 0x5c, 0x20, 0xf1, 0x16, 0xbc, 0x00, 0xef, 0xc1, 0x05, 0xf2, 0x78, 0xdc, 0x38, 0xdd,
	0x00, 0xe2, 0xca, 0x3e, 0xe7, 0x7c, 0xe7, 0xcc, 0x77, 0x66, 0xce, 0x0f, 0x3c, 0x27, 0xa1, 0x77,
	0x12, 0x46, 0x01, 0x0f, 0x26, 0xf1, 0xcd, 0x27, 0x2c, 0xa4, 0xee, 0xc9, 0x32, 0x8c, 0xc7, 0x24,
	0xf4, 0x4c, 0xa1, 0xd5, 0x0f, 0xb6, 0x02, 0x52, 0xa3, 0xa1, 0xc1, 0xee, 0x1b, 0xca, 0x7b, 0x84,
	0x13, 0x4c, 0x97, 0x31, 0x65, 0xdc, 0xe8, 0x42, 0x2b, 0x11, 0x9d, 0x88, 0xf8, 0xec, 0x86, 0x46,
	0x98, 0xb2, 0x30, 0xf0, 0x19, 0x45, 0x1f, 0x83, 0x36, 0xef, 0xae, 0x38, 0x65, 0x89, 0xe5, 0x86,
	0x46, 0x11, 0x9d, 0xb6, 0x95, 0x23, 0xe5, 0x58, 0xc5, 0xef, 0xe8, 0x8d, 0x9f, 0x15, 0x78, 0x4f,
	0xc6, 0x1b, 0xf1, 0x88, 0x92, 0x3b, 0x4c, 0xdd, 0x20, 0x9a, 0xa2, 0x57, 0xb0, 0xb3, 0x8c, 0x69,
	0xb4, 0x92, 0x36, 0xe1, 0xdf, 0xe8, 0x34, 0xcd, 0xab, 0x9c, 0xf2, 0xbc, 0x80, 0x37, 0x40, 0xe8,
	0x00, 0x8a, 0xc4, 0x9d, 0xb7, 0x55, 0x81, 0xad, 0x9a, 0x96, 0x3b, 0xbf, 0x64, 0xb3, 0xf3, 0x02,
	0x4e, 0xb4, 0xe8, 0x19, 0x94, 0x42, 0xcf, 0x9f, 0xb5, 0x8b, 0xc2, 0x5a, 0x33, 0x87, 0x9e, 0x3f,
	0x4b, 0xcd, 0x42, 0xdf, 0xad, 0x43, 0x35, 0x92, 0x89, 0xfd, 0xa5, 0x40, 0x2b, 0xcb, 0x66, 0x83,
	0xd5, 0x73, 0x68, 0xb0, 0x04, 0xe3, 0xbb, 0x74, 0xec, 0xa5, 0x49, 0x15, 0x31, 0x64, 0xaa, 0xfe,
	0x14, 0x9d, 0x42, 0x89, 0xaf, 0x42, 0x2a, 0x28, 0xec, 0x76, 0x5e, 0x98, 0xdb, 0xa2, 0x98, 0x79,
	0xc1, 0x59, 0x85, 0x14, 0x0b, 0x1f, 0xf4, 0x21, 0x94, 0x17, 0xc1, 0x6c, 0x10, 0x4a, 0x86, 0x4f,
	0xcc, 0xe4, 0xee, 0x2f, 0x12, 0x0d, 0x8d, 0x08, 0xf7, 0x02, 0x1f, 0xa7, 0x76, 0xe3, 0x07, 0xd0,
	0x1e, 0x87, 0x40, 0x3b, 0x50, 0xbb, 0x1e, 0xf6, 0x2c, 0xc7, 0x1e, 0x0c, 0xb5, 0x02, 0xda, 0x83,
	0x46, 0x2a, 0xf5, 0xec, 0x0b, 0xc7, 0xd2, 0x14, 0x54, 0x87, 0xf2, 0xc8, 0xb1, 0x1c, 0x5b, 0x53,
	0x51, 0x13, 0xea, 0xe7, 0xb6, 0x85, 0x9d, 0xae, 0x6d, 0x39, 0x5a, 0x11, 0x3d, 0x81, 0xa6, 0xfd,
	0xb6, 0x37, 0x1e, 0x7c, 0x3d, 0x1e, 0x39, 0xd8, 0xb6, 0x2e, 0xb5, 0x92, 0xf1, 0xab, 0x02, 0x3b,
	0xf9, 0x7b, 0x46, 0x87, 0x50, 0x16, 0xf7, 0x2c, 0x5f, 0xa1, 0x22, 0x5f, 0x21, 0x55, 0xa2, 0xcf,
	0xa1, 0x76, 0x47, 0x39, 0x99, 0x12, 0x4e, 0xda, 0xea, 0x51, 0xf1, 0xb8, 0xd1, 0x39, 0xd8, 0x78,
	0x26, 0xf3, 0x52, 0x5a, 0x6d, 0x9f, 0x47, 0x2b, 0xfc, 0x00, 0x46, 0x08, 0x4a, 0x6c, 0xe5, 0xbb,
	0x22, 0xdf, 0x1a, 0x16, 0xff, 0xfa, 0x6b, 0x68, 0x6e, 0xc0, 0x91, 0x06, 0xc5, 0x39, 0x4d, 0x4f,
	0xae, 0xe3, 0xe4, 0x17, 0xb5, 0xa0, 0x7c, 0x4f, 0x16, 0x71, 0x7a, 0xc9, 0x75, 0x9c, 0x0a, 0xa7,
	0xea, 0x17, 0x8a, 0xf1, 0x87, 0x0a, 0x65, 0x71, 0x32, 0x3a, 0x81, 0xaa, 0x20, 0x37, 0xf6, 0x24,
	0xe7, 0x56, 0x4a, 0xc9, 0xf4, 0x7c, 0x4e, 0x23, 0x9f, 0x2c, 0x84, 0x74, 0x5e, 0xc0, 0x15, 0x01,
	0xeb, 0x23, 0x13, 0xea, 0xa9, 0x03, 0x5b, 0x2e, 0x64, 0x01, 0xed, 0x49, 0x97, 0xd1, 0xd5, 0x45,
	0x86, 0xae, 0x09, 0xcc, 0x68, 0xb9, 0xd0, 0x7f, 0x53, 0xa0, 0xb9, 0x11, 0x2b, 0xa1, 0xc5, 0xc9,
	0x64, 0x41, 0x25, 0xd5, 0x54, 0x40, 0xcf, 0x00, 0xc2, 0x28, 0xf8, 0x91, 0xba, 0xc9, 0x03, 0x8a,
	0xeb, 0xa9, 0xe3, 0x9c, 0x06, 0x7d, 0x06, 0xf5, 0x30, 0xa2, 0x53, 0xcf, 0x25, 0x9c, 0xb6, 0x8b,
	0xe2, 0xf6, 0x9e, 0x8a, 0x87, 0xb7, 0x38, 0x8f, 0xbc, 0x49, 0xcc, 0xe9, 0x30, 0x33, 0xe3, 0x35,
	0x12, 0x7d, 0x09, 0x0d, 0xce, 0x1e, 0x2c, 0xed, 0x92, 0x20, 0xac, 0x0b, 0xc7, 0x91, 0x4f, 0x42,
	0x76, 0x1b, 0x70, 0xc7, 0xbb, 0xcb, 0xf9, 0xe6, 0xe1, 0xfa, 0x0b, 0xa8, 0x65, 0x49, 0x21, 0x1d,
	0x64, 0x52, 0x3c, 0x92, 0xcc, 0x1f, 0xe4, 0x6e, 0x19, 0x8a, 0xf7, 0x64, 0x61, 0x7c, 0x04, 0x95,
	0xb4, 0x95, 0xfe, 0xb3, 0xfe, 0x0d, 0x0b, 0x9a, 0x67, 0x81, 0x7f, 0xe3, 0xcd, 0xb2, 0xd2, 0x79,
	0x09, 0x65, 0x77, 0x11, 0xb8, 0x73, 0xf9, 0x0c, 0xff, 0x46, 0x31, 0x05, 0x1a, 0x7f, 0x2a, 0xb0,
	0x9b, 0xc5, 0x90, 0x03, 0xa5, 0x03, 0xb5, 0x64, 0x50, 0x89, 0xce, 0x52, 0x44, 0x67, 0x3d, 0x35,
	0x37, 0x21, 0xe6, 0xd5, 0xf0, 0x5a, 0xb4, 0x52, 0x75, 0x19, 0xc6, 0xa2, 0x21, 0xce, 0x40, 0x63,
	0x71, 0x18, 0x06, 0x11, 0xa7, 0xd3, 0x24, 0x53, 0x8f, 0x32, 0x59, 0x9d, 0xff, 0x78, 0xbf, 0xef,
	0x38, 0x20, 0x03, 0xaa, 0x49, 0x25, 0x32, 0xca, 0x1f, 0xc6, 0x46, 0x32, 0xf1, 0x46, 0x94, 0xe3,
	0xcc, 0x60, 0x74, 0xa0, 0x2a, 0x0f, 0x47, 0x2d, 0xd0, 0x7a, 0x96, 0x63, 0x8d, 0x9c, 0x01, 0xb6,
	0xc7, 0x3d, 0xdc, 0xff, 0xce, 0xc6, 0x5a, 0x01, 0x55, 0xa1, 0x38, 0xba, 0xbe, 0xd4, 0x14, 0x54,
	0x83, 0xd2, 0x37, 0x83, 0xfe, 0x5b, 0x4d, 0x35, 0x7e, 0x57, 0xa1, 0x2a, 0x03, 0x25, 0x15, 0x90,
	0x84, 0x9a, 0x10, 0x46, 0x59, 0x5b, 0x91, 0x0c, 0xa5, 0x51, 0x7c, 0x85, 0x25, 0xed, 0x9d, 0x35,
	0x52, 0xff, 0x49, 0x01, 0xb5, 0xd7, 0x45, 0x5f, 0x41, 0x23, 0xd1, 0xb9, 0x34, 0xa9, 0xc5, 0xcc,
	0xff, 0x70, 0xed, 0xdf, 0x15, 0xbf, 0xd2, 0x9c, 0x06, 0xc9, 0x3b, 0xe8, 0xdf, 0x82, 0xf6, 0x18,
	0xb0, 0xa5, 0xe5, 0x3e, 0xc8, 0xb7, 0x5c, 0xa3, 0xd3, 0x58, 0xc7, 0x3f, 0xcb, 0xf5, 0x9f, 0x7e,
	0x08, 0x6a, 0xef, 0x0c, 0xbd, 0x0f, 0x15, 0x76, 0x4b, 0xa2, 0x69, 0xca, 0xa6, 0x8e, 0xa5, 0xa4,
	0xf7, 0x61, 0x77, 0x33, 0x9d, 0xff, 0x75, 0x50, 0x37, 0xdf, 0xe8, 0x47, 0x50, 0x95, 0xe3, 0x1b,
	0xed, 0x43, 0x85, 0xd1, 0xe5, 0xba, 0x1a, 0xcb, 0x8c, 0x2e, 0xfb, 0xd3, 0xce, 0x2f, 0x0a, 0x54,
	0xae, 0x86, 0xd7, 0xd6, 0xb0, 0x8f, 0x4e, 0xb3, 0xa1, 0xd0, 0x32, 0xb7, 0x6c, 0x1a, 0x7d, 0x7f,
	0xeb, 0x90, 0x36, 0x0a, 0xc7, 0xca, 0x4b, 0x25, 0x19, 0x0b, 0x6f, 0x28, 0x4f, 0x6b, 0x0d, 0xed,
	0x9a, 0x1b, 0xb5, 0xad, 0xef, 0x3d, 0x2a, 0x42, 0xa3, 0x80, 0x5e, 0xc3, 0x9e, 0x5c, 0x92, 0xd9,
	0x56, 0x44, 0x7b, 0xe6, 0xe6, 0xda, 0xd4, 0xf7, 0xcd, 0x6d, 0x5b, 0xd3, 0x28, 0x74, 0x3f, 0xfd,
	0xbe, 0x33, 0xf3, 0xf8, 0x6d, 0x3c, 0x31, 0xdd, 0xe0, 0xee, 0x64, 0x7a, 0x4f, 0x98, 0xb7, 0x20,
	0x4c, 0x2c, 0x64, 0x1a, 0xb3, 0x93, 0x6c, 0xdc, 0xa4, 0x1b, 0x3a, 0x5b, 0xdd, 0x93, 0x8a, 0x10,
	0x5f, 0xfd, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x89, 0x31, 0xb1, 0x7e, 0xde, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QPUAPIClient is the client API for QPUAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QPUAPIClient interface {
	Query(ctx context.Context, opts ...grpc.CallOption) (QPUAPI_QueryClient, error)
	GetConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error)
	GetDataTransfer(ctx context.Context, in *GetDataRequest, opts ...grpc.CallOption) (*DataTransferResponse, error)
}

type qPUAPIClient struct {
	cc *grpc.ClientConn
}

func NewQPUAPIClient(cc *grpc.ClientConn) QPUAPIClient {
	return &qPUAPIClient{cc}
}

func (c *qPUAPIClient) Query(ctx context.Context, opts ...grpc.CallOption) (QPUAPI_QueryClient, error) {
	stream, err := c.cc.NewStream(ctx, &_QPUAPI_serviceDesc.Streams[0], "/QPUAPI/Query", opts...)
	if err != nil {
		return nil, err
	}
	x := &qPUAPIQueryClient{stream}
	return x, nil
}

type QPUAPI_QueryClient interface {
	Send(*RequestStreamRecord) error
	Recv() (*ResponseStreamRecord, error)
	grpc.ClientStream
}

type qPUAPIQueryClient struct {
	grpc.ClientStream
}

func (x *qPUAPIQueryClient) Send(m *RequestStreamRecord) error {
	return x.ClientStream.SendMsg(m)
}

func (x *qPUAPIQueryClient) Recv() (*ResponseStreamRecord, error) {
	m := new(ResponseStreamRecord)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *qPUAPIClient) GetConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error) {
	out := new(ConfigResponse)
	err := c.cc.Invoke(ctx, "/QPUAPI/GetConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qPUAPIClient) GetDataTransfer(ctx context.Context, in *GetDataRequest, opts ...grpc.CallOption) (*DataTransferResponse, error) {
	out := new(DataTransferResponse)
	err := c.cc.Invoke(ctx, "/QPUAPI/GetDataTransfer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QPUAPIServer is the server API for QPUAPI service.
type QPUAPIServer interface {
	Query(QPUAPI_QueryServer) error
	GetConfig(context.Context, *ConfigRequest) (*ConfigResponse, error)
	GetDataTransfer(context.Context, *GetDataRequest) (*DataTransferResponse, error)
}

func RegisterQPUAPIServer(s *grpc.Server, srv QPUAPIServer) {
	s.RegisterService(&_QPUAPI_serviceDesc, srv)
}

func _QPUAPI_Query_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(QPUAPIServer).Query(&qPUAPIQueryServer{stream})
}

type QPUAPI_QueryServer interface {
	Send(*ResponseStreamRecord) error
	Recv() (*RequestStreamRecord, error)
	grpc.ServerStream
}

type qPUAPIQueryServer struct {
	grpc.ServerStream
}

func (x *qPUAPIQueryServer) Send(m *ResponseStreamRecord) error {
	return x.ServerStream.SendMsg(m)
}

func (x *qPUAPIQueryServer) Recv() (*RequestStreamRecord, error) {
	m := new(RequestStreamRecord)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _QPUAPI_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QPUAPIServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/QPUAPI/GetConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QPUAPIServer).GetConfig(ctx, req.(*ConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QPUAPI_GetDataTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QPUAPIServer).GetDataTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/QPUAPI/GetDataTransfer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QPUAPIServer).GetDataTransfer(ctx, req.(*GetDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _QPUAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "QPUAPI",
	HandlerType: (*QPUAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConfig",
			Handler:    _QPUAPI_GetConfig_Handler,
		},
		{
			MethodName: "GetDataTransfer",
			Handler:    _QPUAPI_GetDataTransfer_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Query",
			Handler:       _QPUAPI_Query_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/protobuf-spec/qpu_api.proto",
}
