// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/protobuf-spec/client_api.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type QueryReq struct {
	QueryStr             string   `protobuf:"bytes,1,opt,name=queryStr,proto3" json:"queryStr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryReq) Reset()         { *m = QueryReq{} }
func (m *QueryReq) String() string { return proto.CompactTextString(m) }
func (*QueryReq) ProtoMessage()    {}
func (*QueryReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a58988a9bf4976bc, []int{0}
}

func (m *QueryReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryReq.Unmarshal(m, b)
}
func (m *QueryReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryReq.Marshal(b, m, deterministic)
}
func (m *QueryReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryReq.Merge(m, src)
}
func (m *QueryReq) XXX_Size() int {
	return xxx_messageInfo_QueryReq.Size(m)
}
func (m *QueryReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryReq.DiscardUnknown(m)
}

var xxx_messageInfo_QueryReq proto.InternalMessageInfo

func (m *QueryReq) GetQueryStr() string {
	if m != nil {
		return m.QueryStr
	}
	return ""
}

type QueryResp struct {
	RespRecord           []*QueryRespRecord `protobuf:"bytes,1,rep,name=respRecord,proto3" json:"respRecord,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *QueryResp) Reset()         { *m = QueryResp{} }
func (m *QueryResp) String() string { return proto.CompactTextString(m) }
func (*QueryResp) ProtoMessage()    {}
func (*QueryResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a58988a9bf4976bc, []int{1}
}

func (m *QueryResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResp.Unmarshal(m, b)
}
func (m *QueryResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResp.Marshal(b, m, deterministic)
}
func (m *QueryResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResp.Merge(m, src)
}
func (m *QueryResp) XXX_Size() int {
	return xxx_messageInfo_QueryResp.Size(m)
}
func (m *QueryResp) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResp.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResp proto.InternalMessageInfo

func (m *QueryResp) GetRespRecord() []*QueryRespRecord {
	if m != nil {
		return m.RespRecord
	}
	return nil
}

type QueryRespRecord struct {
	RecordId             string                          `protobuf:"bytes,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	Attributes           map[string][]byte               `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Timestamp            map[string]*timestamp.Timestamp `protobuf:"bytes,4,rep,name=timestamp,proto3" json:"timestamp,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *QueryRespRecord) Reset()         { *m = QueryRespRecord{} }
func (m *QueryRespRecord) String() string { return proto.CompactTextString(m) }
func (*QueryRespRecord) ProtoMessage()    {}
func (*QueryRespRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_a58988a9bf4976bc, []int{2}
}

func (m *QueryRespRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRespRecord.Unmarshal(m, b)
}
func (m *QueryRespRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRespRecord.Marshal(b, m, deterministic)
}
func (m *QueryRespRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRespRecord.Merge(m, src)
}
func (m *QueryRespRecord) XXX_Size() int {
	return xxx_messageInfo_QueryRespRecord.Size(m)
}
func (m *QueryRespRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRespRecord.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRespRecord proto.InternalMessageInfo

func (m *QueryRespRecord) GetRecordId() string {
	if m != nil {
		return m.RecordId
	}
	return ""
}

func (m *QueryRespRecord) GetAttributes() map[string][]byte {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *QueryRespRecord) GetTimestamp() map[string]*timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryReq)(nil), "pb.QueryReq")
	proto.RegisterType((*QueryResp)(nil), "pb.QueryResp")
	proto.RegisterType((*QueryRespRecord)(nil), "pb.QueryRespRecord")
	proto.RegisterMapType((map[string][]byte)(nil), "pb.QueryRespRecord.AttributesEntry")
	proto.RegisterMapType((map[string]*timestamp.Timestamp)(nil), "pb.QueryRespRecord.TimestampEntry")
}

func init() { proto.RegisterFile("api/protobuf-spec/client_api.proto", fileDescriptor_a58988a9bf4976bc) }

var fileDescriptor_a58988a9bf4976bc = []byte{
	// 362 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x4f, 0x4f, 0xfa, 0x30,
	0x18, 0xfe, 0x6d, 0xfc, 0x24, 0xec, 0x05, 0xc5, 0x54, 0x0f, 0xcb, 0x3c, 0x48, 0x66, 0x62, 0x48,
	0x0c, 0x9b, 0x01, 0x35, 0xc6, 0xc4, 0x04, 0x34, 0x1e, 0xb8, 0xc1, 0x94, 0xc4, 0x78, 0x21, 0xdd,
	0x56, 0x67, 0xc3, 0x60, 0xa5, 0xed, 0x48, 0xf6, 0x25, 0xfd, 0x4c, 0x86, 0x8d, 0x8d, 0x41, 0xb8,
	0x3d, 0xed, 0xfb, 0xfc, 0x79, 0x9f, 0xb4, 0x60, 0x62, 0x46, 0x6d, 0xc6, 0x23, 0x19, 0xb9, 0xf1,
	0x77, 0x47, 0x30, 0xe2, 0xd9, 0x5e, 0x48, 0xc9, 0x42, 0x4e, 0x31, 0xa3, 0x56, 0x3a, 0x40, 0x2a,
	0x73, 0x8d, 0xcb, 0x20, 0x8a, 0x82, 0x90, 0x14, 0x54, 0x5b, 0xd2, 0x39, 0x11, 0x12, 0xcf, 0x59,
	0x46, 0x32, 0xaf, 0xa1, 0x36, 0x8e, 0x09, 0x4f, 0x1c, 0xb2, 0x44, 0x06, 0xd4, 0x96, 0x6b, 0xfc,
	0x2e, 0xb9, 0xae, 0xb4, 0x94, 0xb6, 0xe6, 0x14, 0x67, 0xb3, 0x0f, 0xda, 0x86, 0x27, 0x18, 0xea,
	0x01, 0x70, 0x22, 0x98, 0x43, 0xbc, 0x88, 0xfb, 0xba, 0xd2, 0xaa, 0xb4, 0xeb, 0xdd, 0x33, 0x8b,
	0xb9, 0x56, 0x41, 0xc9, 0x46, 0x4e, 0x89, 0x66, 0xfe, 0xaa, 0xd0, 0xdc, 0x9b, 0xa3, 0x0b, 0xd0,
	0x78, 0x8a, 0xa6, 0xd4, 0xcf, 0x23, 0xb3, 0x8b, 0xa1, 0x8f, 0x5e, 0x01, 0xb0, 0x94, 0x9c, 0xba,
	0xb1, 0x24, 0x42, 0xaf, 0xa4, 0x29, 0x57, 0x07, 0x52, 0xac, 0x41, 0xc1, 0x7a, 0x5b, 0x48, 0x9e,
	0x38, 0x25, 0x19, 0xea, 0x83, 0x56, 0x54, 0xd6, 0xff, 0xa7, 0x1e, 0xe6, 0x21, 0x8f, 0x8f, 0x9c,
	0x94, 0x59, 0x6c, 0x45, 0xc6, 0x33, 0x34, 0xf7, 0x02, 0xd0, 0x29, 0x54, 0x66, 0x24, 0xd9, 0x2c,
	0xbc, 0x86, 0xe8, 0x1c, 0x8e, 0x56, 0x38, 0x8c, 0x89, 0xae, 0xb6, 0x94, 0x76, 0xc3, 0xc9, 0x0e,
	0x4f, 0xea, 0xa3, 0x62, 0x7c, 0xc2, 0xc9, 0xae, 0xf7, 0x01, 0xf5, 0x6d, 0x59, 0x5d, 0xef, 0x1a,
	0x56, 0xf6, 0x6a, 0x56, 0xfe, 0x6a, 0xdb, 0xed, 0x4a, 0xce, 0xdd, 0x7b, 0xa8, 0x8e, 0x47, 0x93,
	0xc1, 0x68, 0x88, 0x6e, 0x00, 0xd2, 0x3e, 0x93, 0x05, 0xe6, 0x09, 0x6a, 0x94, 0xfa, 0x2d, 0x8d,
	0xe3, 0x9d, 0xb6, 0xe6, 0xbf, 0x97, 0x87, 0xaf, 0xbb, 0x80, 0xca, 0x9f, 0xd8, 0xb5, 0xbc, 0x68,
	0x6e, 0xfb, 0x2b, 0x2c, 0x68, 0x88, 0x45, 0xfa, 0x43, 0x48, 0x2c, 0x6c, 0x36, 0x0b, 0x72, 0xdc,
	0x09, 0xa2, 0x4e, 0xf6, 0xab, 0x6c, 0xe6, 0xba, 0xd5, 0x74, 0x9b, 0xde, 0x5f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xb0, 0xf5, 0x05, 0x81, 0x7b, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QPUAPIClient is the client API for QPUAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QPUAPIClient interface {
	QueryUnary(ctx context.Context, in *QueryReq, opts ...grpc.CallOption) (*QueryResp, error)
}

type qPUAPIClient struct {
	cc *grpc.ClientConn
}

func NewQPUAPIClient(cc *grpc.ClientConn) QPUAPIClient {
	return &qPUAPIClient{cc}
}

func (c *qPUAPIClient) QueryUnary(ctx context.Context, in *QueryReq, opts ...grpc.CallOption) (*QueryResp, error) {
	out := new(QueryResp)
	err := c.cc.Invoke(ctx, "/pb.QPUAPI/QueryUnary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QPUAPIServer is the server API for QPUAPI service.
type QPUAPIServer interface {
	QueryUnary(context.Context, *QueryReq) (*QueryResp, error)
}

func RegisterQPUAPIServer(s *grpc.Server, srv QPUAPIServer) {
	s.RegisterService(&_QPUAPI_serviceDesc, srv)
}

func _QPUAPI_QueryUnary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QPUAPIServer).QueryUnary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.QPUAPI/QueryUnary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QPUAPIServer).QueryUnary(ctx, req.(*QueryReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _QPUAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.QPUAPI",
	HandlerType: (*QPUAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryUnary",
			Handler:    _QPUAPI_QueryUnary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/protobuf-spec/client_api.proto",
}
