// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/protobuf-spec/qpuextapi.proto

package qpuextapi

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Payload_PayloadType int32

const (
	Payload_STRING Payload_PayloadType = 0
	Payload_INT    Payload_PayloadType = 1
	Payload_FLOAT  Payload_PayloadType = 2
)

var Payload_PayloadType_name = map[int32]string{
	0: "STRING",
	1: "INT",
	2: "FLOAT",
}

var Payload_PayloadType_value = map[string]int32{
	"STRING": 0,
	"INT":    1,
	"FLOAT":  2,
}

func (x Payload_PayloadType) String() string {
	return proto.EnumName(Payload_PayloadType_name, int32(x))
}

func (Payload_PayloadType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_dc3d4fb1c88266a9, []int{4, 0}
}

type QueryReq struct {
	QueryStr             string   `protobuf:"bytes,1,opt,name=queryStr,proto3" json:"queryStr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryReq) Reset()         { *m = QueryReq{} }
func (m *QueryReq) String() string { return proto.CompactTextString(m) }
func (*QueryReq) ProtoMessage()    {}
func (*QueryReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc3d4fb1c88266a9, []int{0}
}

func (m *QueryReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryReq.Unmarshal(m, b)
}
func (m *QueryReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryReq.Marshal(b, m, deterministic)
}
func (m *QueryReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryReq.Merge(m, src)
}
func (m *QueryReq) XXX_Size() int {
	return xxx_messageInfo_QueryReq.Size(m)
}
func (m *QueryReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryReq.DiscardUnknown(m)
}

var xxx_messageInfo_QueryReq proto.InternalMessageInfo

func (m *QueryReq) GetQueryStr() string {
	if m != nil {
		return m.QueryStr
	}
	return ""
}

type QueryResp struct {
	RespRecord           []*QueryRespRecord `protobuf:"bytes,1,rep,name=respRecord,proto3" json:"respRecord,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *QueryResp) Reset()         { *m = QueryResp{} }
func (m *QueryResp) String() string { return proto.CompactTextString(m) }
func (*QueryResp) ProtoMessage()    {}
func (*QueryResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc3d4fb1c88266a9, []int{1}
}

func (m *QueryResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResp.Unmarshal(m, b)
}
func (m *QueryResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResp.Marshal(b, m, deterministic)
}
func (m *QueryResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResp.Merge(m, src)
}
func (m *QueryResp) XXX_Size() int {
	return xxx_messageInfo_QueryResp.Size(m)
}
func (m *QueryResp) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResp.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResp proto.InternalMessageInfo

func (m *QueryResp) GetRespRecord() []*QueryRespRecord {
	if m != nil {
		return m.RespRecord
	}
	return nil
}

type QueryResp1 struct {
	RespRecord           []*QueryRespRecord1 `protobuf:"bytes,1,rep,name=respRecord,proto3" json:"respRecord,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *QueryResp1) Reset()         { *m = QueryResp1{} }
func (m *QueryResp1) String() string { return proto.CompactTextString(m) }
func (*QueryResp1) ProtoMessage()    {}
func (*QueryResp1) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc3d4fb1c88266a9, []int{2}
}

func (m *QueryResp1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResp1.Unmarshal(m, b)
}
func (m *QueryResp1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResp1.Marshal(b, m, deterministic)
}
func (m *QueryResp1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResp1.Merge(m, src)
}
func (m *QueryResp1) XXX_Size() int {
	return xxx_messageInfo_QueryResp1.Size(m)
}
func (m *QueryResp1) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResp1.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResp1 proto.InternalMessageInfo

func (m *QueryResp1) GetRespRecord() []*QueryRespRecord1 {
	if m != nil {
		return m.RespRecord
	}
	return nil
}

type QueryRespRecord1 struct {
	Response             map[string]*Payload             `protobuf:"bytes,1,rep,name=response,proto3" json:"response,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Timestamp            map[string]*timestamp.Timestamp `protobuf:"bytes,2,rep,name=timestamp,proto3" json:"timestamp,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *QueryRespRecord1) Reset()         { *m = QueryRespRecord1{} }
func (m *QueryRespRecord1) String() string { return proto.CompactTextString(m) }
func (*QueryRespRecord1) ProtoMessage()    {}
func (*QueryRespRecord1) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc3d4fb1c88266a9, []int{3}
}

func (m *QueryRespRecord1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRespRecord1.Unmarshal(m, b)
}
func (m *QueryRespRecord1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRespRecord1.Marshal(b, m, deterministic)
}
func (m *QueryRespRecord1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRespRecord1.Merge(m, src)
}
func (m *QueryRespRecord1) XXX_Size() int {
	return xxx_messageInfo_QueryRespRecord1.Size(m)
}
func (m *QueryRespRecord1) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRespRecord1.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRespRecord1 proto.InternalMessageInfo

func (m *QueryRespRecord1) GetResponse() map[string]*Payload {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *QueryRespRecord1) GetTimestamp() map[string]*timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type Payload struct {
	Type                 Payload_PayloadType `protobuf:"varint,1,opt,name=type,proto3,enum=qpuextapi.Payload_PayloadType" json:"type,omitempty"`
	Value                []byte              `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Payload) Reset()         { *m = Payload{} }
func (m *Payload) String() string { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()    {}
func (*Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc3d4fb1c88266a9, []int{4}
}

func (m *Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload.Unmarshal(m, b)
}
func (m *Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload.Marshal(b, m, deterministic)
}
func (m *Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload.Merge(m, src)
}
func (m *Payload) XXX_Size() int {
	return xxx_messageInfo_Payload.Size(m)
}
func (m *Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_Payload proto.InternalMessageInfo

func (m *Payload) GetType() Payload_PayloadType {
	if m != nil {
		return m.Type
	}
	return Payload_STRING
}

func (m *Payload) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type QueryRespRecord struct {
	RecordId             string                          `protobuf:"bytes,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	Attributes           map[string]string               `protobuf:"bytes,2,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Timestamp            map[string]*timestamp.Timestamp `protobuf:"bytes,3,rep,name=timestamp,proto3" json:"timestamp,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *QueryRespRecord) Reset()         { *m = QueryRespRecord{} }
func (m *QueryRespRecord) String() string { return proto.CompactTextString(m) }
func (*QueryRespRecord) ProtoMessage()    {}
func (*QueryRespRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc3d4fb1c88266a9, []int{5}
}

func (m *QueryRespRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRespRecord.Unmarshal(m, b)
}
func (m *QueryRespRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRespRecord.Marshal(b, m, deterministic)
}
func (m *QueryRespRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRespRecord.Merge(m, src)
}
func (m *QueryRespRecord) XXX_Size() int {
	return xxx_messageInfo_QueryRespRecord.Size(m)
}
func (m *QueryRespRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRespRecord.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRespRecord proto.InternalMessageInfo

func (m *QueryRespRecord) GetRecordId() string {
	if m != nil {
		return m.RecordId
	}
	return ""
}

func (m *QueryRespRecord) GetAttributes() map[string]string {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *QueryRespRecord) GetTimestamp() map[string]*timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type MetricsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetricsRequest) Reset()         { *m = MetricsRequest{} }
func (m *MetricsRequest) String() string { return proto.CompactTextString(m) }
func (*MetricsRequest) ProtoMessage()    {}
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc3d4fb1c88266a9, []int{6}
}

func (m *MetricsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricsRequest.Unmarshal(m, b)
}
func (m *MetricsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricsRequest.Marshal(b, m, deterministic)
}
func (m *MetricsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricsRequest.Merge(m, src)
}
func (m *MetricsRequest) XXX_Size() int {
	return xxx_messageInfo_MetricsRequest.Size(m)
}
func (m *MetricsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MetricsRequest proto.InternalMessageInfo

type MetricsResponse struct {
	NotificationLatencyP50 float64  `protobuf:"fixed64,1,opt,name=notificationLatencyP50,proto3" json:"notificationLatencyP50,omitempty"`
	NotificationLatencyP90 float64  `protobuf:"fixed64,2,opt,name=notificationLatencyP90,proto3" json:"notificationLatencyP90,omitempty"`
	NotificationLatencyP95 float64  `protobuf:"fixed64,3,opt,name=notificationLatencyP95,proto3" json:"notificationLatencyP95,omitempty"`
	NotificationLatencyP99 float64  `protobuf:"fixed64,4,opt,name=notificationLatencyP99,proto3" json:"notificationLatencyP99,omitempty"`
	ProcessingLatencyP50   float64  `protobuf:"fixed64,5,opt,name=processingLatencyP50,proto3" json:"processingLatencyP50,omitempty"`
	ProcessingLatencyP90   float64  `protobuf:"fixed64,6,opt,name=processingLatencyP90,proto3" json:"processingLatencyP90,omitempty"`
	ProcessingLatencyP95   float64  `protobuf:"fixed64,7,opt,name=processingLatencyP95,proto3" json:"processingLatencyP95,omitempty"`
	ProcessingLatencyP99   float64  `protobuf:"fixed64,8,opt,name=processingLatencyP99,proto3" json:"processingLatencyP99,omitempty"`
	FreshnessLatencyP50    float64  `protobuf:"fixed64,9,opt,name=freshnessLatencyP50,proto3" json:"freshnessLatencyP50,omitempty"`
	FreshnessLatencyP90    float64  `protobuf:"fixed64,10,opt,name=freshnessLatencyP90,proto3" json:"freshnessLatencyP90,omitempty"`
	FreshnessLatencyP95    float64  `protobuf:"fixed64,11,opt,name=freshnessLatencyP95,proto3" json:"freshnessLatencyP95,omitempty"`
	FreshnessLatencyP99    float64  `protobuf:"fixed64,12,opt,name=freshnessLatencyP99,proto3" json:"freshnessLatencyP99,omitempty"`
	FreshnessVersions0     float64  `protobuf:"fixed64,13,opt,name=freshnessVersions0,proto3" json:"freshnessVersions0,omitempty"`
	FreshnessVersions1     float64  `protobuf:"fixed64,14,opt,name=freshnessVersions1,proto3" json:"freshnessVersions1,omitempty"`
	FreshnessVersions2     float64  `protobuf:"fixed64,15,opt,name=freshnessVersions2,proto3" json:"freshnessVersions2,omitempty"`
	FreshnessVersions4     float64  `protobuf:"fixed64,16,opt,name=freshnessVersions4,proto3" json:"freshnessVersions4,omitempty"`
	StateUpdateLatencyP50  float64  `protobuf:"fixed64,17,opt,name=stateUpdateLatencyP50,proto3" json:"stateUpdateLatencyP50,omitempty"`
	StateUpdateLatencyP90  float64  `protobuf:"fixed64,18,opt,name=stateUpdateLatencyP90,proto3" json:"stateUpdateLatencyP90,omitempty"`
	StateUpdateLatencyP95  float64  `protobuf:"fixed64,19,opt,name=stateUpdateLatencyP95,proto3" json:"stateUpdateLatencyP95,omitempty"`
	StateUpdateLatencyP99  float64  `protobuf:"fixed64,20,opt,name=stateUpdateLatencyP99,proto3" json:"stateUpdateLatencyP99,omitempty"`
	KBytesSent             float64  `protobuf:"fixed64,21,opt,name=kBytesSent,proto3" json:"kBytesSent,omitempty"`
	ResponseTimeP50        float64  `protobuf:"fixed64,22,opt,name=responseTimeP50,proto3" json:"responseTimeP50,omitempty"`
	ResponseTimeP90        float64  `protobuf:"fixed64,23,opt,name=responseTimeP90,proto3" json:"responseTimeP90,omitempty"`
	ResponseTimeP95        float64  `protobuf:"fixed64,24,opt,name=responseTimeP95,proto3" json:"responseTimeP95,omitempty"`
	ResponseTimeP99        float64  `protobuf:"fixed64,25,opt,name=responseTimeP99,proto3" json:"responseTimeP99,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *MetricsResponse) Reset()         { *m = MetricsResponse{} }
func (m *MetricsResponse) String() string { return proto.CompactTextString(m) }
func (*MetricsResponse) ProtoMessage()    {}
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc3d4fb1c88266a9, []int{7}
}

func (m *MetricsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricsResponse.Unmarshal(m, b)
}
func (m *MetricsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricsResponse.Marshal(b, m, deterministic)
}
func (m *MetricsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricsResponse.Merge(m, src)
}
func (m *MetricsResponse) XXX_Size() int {
	return xxx_messageInfo_MetricsResponse.Size(m)
}
func (m *MetricsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MetricsResponse proto.InternalMessageInfo

func (m *MetricsResponse) GetNotificationLatencyP50() float64 {
	if m != nil {
		return m.NotificationLatencyP50
	}
	return 0
}

func (m *MetricsResponse) GetNotificationLatencyP90() float64 {
	if m != nil {
		return m.NotificationLatencyP90
	}
	return 0
}

func (m *MetricsResponse) GetNotificationLatencyP95() float64 {
	if m != nil {
		return m.NotificationLatencyP95
	}
	return 0
}

func (m *MetricsResponse) GetNotificationLatencyP99() float64 {
	if m != nil {
		return m.NotificationLatencyP99
	}
	return 0
}

func (m *MetricsResponse) GetProcessingLatencyP50() float64 {
	if m != nil {
		return m.ProcessingLatencyP50
	}
	return 0
}

func (m *MetricsResponse) GetProcessingLatencyP90() float64 {
	if m != nil {
		return m.ProcessingLatencyP90
	}
	return 0
}

func (m *MetricsResponse) GetProcessingLatencyP95() float64 {
	if m != nil {
		return m.ProcessingLatencyP95
	}
	return 0
}

func (m *MetricsResponse) GetProcessingLatencyP99() float64 {
	if m != nil {
		return m.ProcessingLatencyP99
	}
	return 0
}

func (m *MetricsResponse) GetFreshnessLatencyP50() float64 {
	if m != nil {
		return m.FreshnessLatencyP50
	}
	return 0
}

func (m *MetricsResponse) GetFreshnessLatencyP90() float64 {
	if m != nil {
		return m.FreshnessLatencyP90
	}
	return 0
}

func (m *MetricsResponse) GetFreshnessLatencyP95() float64 {
	if m != nil {
		return m.FreshnessLatencyP95
	}
	return 0
}

func (m *MetricsResponse) GetFreshnessLatencyP99() float64 {
	if m != nil {
		return m.FreshnessLatencyP99
	}
	return 0
}

func (m *MetricsResponse) GetFreshnessVersions0() float64 {
	if m != nil {
		return m.FreshnessVersions0
	}
	return 0
}

func (m *MetricsResponse) GetFreshnessVersions1() float64 {
	if m != nil {
		return m.FreshnessVersions1
	}
	return 0
}

func (m *MetricsResponse) GetFreshnessVersions2() float64 {
	if m != nil {
		return m.FreshnessVersions2
	}
	return 0
}

func (m *MetricsResponse) GetFreshnessVersions4() float64 {
	if m != nil {
		return m.FreshnessVersions4
	}
	return 0
}

func (m *MetricsResponse) GetStateUpdateLatencyP50() float64 {
	if m != nil {
		return m.StateUpdateLatencyP50
	}
	return 0
}

func (m *MetricsResponse) GetStateUpdateLatencyP90() float64 {
	if m != nil {
		return m.StateUpdateLatencyP90
	}
	return 0
}

func (m *MetricsResponse) GetStateUpdateLatencyP95() float64 {
	if m != nil {
		return m.StateUpdateLatencyP95
	}
	return 0
}

func (m *MetricsResponse) GetStateUpdateLatencyP99() float64 {
	if m != nil {
		return m.StateUpdateLatencyP99
	}
	return 0
}

func (m *MetricsResponse) GetKBytesSent() float64 {
	if m != nil {
		return m.KBytesSent
	}
	return 0
}

func (m *MetricsResponse) GetResponseTimeP50() float64 {
	if m != nil {
		return m.ResponseTimeP50
	}
	return 0
}

func (m *MetricsResponse) GetResponseTimeP90() float64 {
	if m != nil {
		return m.ResponseTimeP90
	}
	return 0
}

func (m *MetricsResponse) GetResponseTimeP95() float64 {
	if m != nil {
		return m.ResponseTimeP95
	}
	return 0
}

func (m *MetricsResponse) GetResponseTimeP99() float64 {
	if m != nil {
		return m.ResponseTimeP99
	}
	return 0
}

type Story struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ShortID              string   `protobuf:"bytes,3,opt,name=shortID,proto3" json:"shortID,omitempty"`
	VoteCount            int64    `protobuf:"varint,4,opt,name=voteCount,proto3" json:"voteCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Story) Reset()         { *m = Story{} }
func (m *Story) String() string { return proto.CompactTextString(m) }
func (*Story) ProtoMessage()    {}
func (*Story) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc3d4fb1c88266a9, []int{8}
}

func (m *Story) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Story.Unmarshal(m, b)
}
func (m *Story) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Story.Marshal(b, m, deterministic)
}
func (m *Story) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Story.Merge(m, src)
}
func (m *Story) XXX_Size() int {
	return xxx_messageInfo_Story.Size(m)
}
func (m *Story) XXX_DiscardUnknown() {
	xxx_messageInfo_Story.DiscardUnknown(m)
}

var xxx_messageInfo_Story proto.InternalMessageInfo

func (m *Story) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Story) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Story) GetShortID() string {
	if m != nil {
		return m.ShortID
	}
	return ""
}

func (m *Story) GetVoteCount() int64 {
	if m != nil {
		return m.VoteCount
	}
	return 0
}

type LobFrontpageReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LobFrontpageReq) Reset()         { *m = LobFrontpageReq{} }
func (m *LobFrontpageReq) String() string { return proto.CompactTextString(m) }
func (*LobFrontpageReq) ProtoMessage()    {}
func (*LobFrontpageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc3d4fb1c88266a9, []int{9}
}

func (m *LobFrontpageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LobFrontpageReq.Unmarshal(m, b)
}
func (m *LobFrontpageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LobFrontpageReq.Marshal(b, m, deterministic)
}
func (m *LobFrontpageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LobFrontpageReq.Merge(m, src)
}
func (m *LobFrontpageReq) XXX_Size() int {
	return xxx_messageInfo_LobFrontpageReq.Size(m)
}
func (m *LobFrontpageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LobFrontpageReq.DiscardUnknown(m)
}

var xxx_messageInfo_LobFrontpageReq proto.InternalMessageInfo

type LobFrontpageResp struct {
	Stories              []*Story `protobuf:"bytes,1,rep,name=stories,proto3" json:"stories,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LobFrontpageResp) Reset()         { *m = LobFrontpageResp{} }
func (m *LobFrontpageResp) String() string { return proto.CompactTextString(m) }
func (*LobFrontpageResp) ProtoMessage()    {}
func (*LobFrontpageResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc3d4fb1c88266a9, []int{10}
}

func (m *LobFrontpageResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LobFrontpageResp.Unmarshal(m, b)
}
func (m *LobFrontpageResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LobFrontpageResp.Marshal(b, m, deterministic)
}
func (m *LobFrontpageResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LobFrontpageResp.Merge(m, src)
}
func (m *LobFrontpageResp) XXX_Size() int {
	return xxx_messageInfo_LobFrontpageResp.Size(m)
}
func (m *LobFrontpageResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LobFrontpageResp.DiscardUnknown(m)
}

var xxx_messageInfo_LobFrontpageResp proto.InternalMessageInfo

func (m *LobFrontpageResp) GetStories() []*Story {
	if m != nil {
		return m.Stories
	}
	return nil
}

type LobStoryVoteReq struct {
	StoryID              int64    `protobuf:"varint,1,opt,name=storyID,proto3" json:"storyID,omitempty"`
	Vote                 int64    `protobuf:"varint,2,opt,name=vote,proto3" json:"vote,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LobStoryVoteReq) Reset()         { *m = LobStoryVoteReq{} }
func (m *LobStoryVoteReq) String() string { return proto.CompactTextString(m) }
func (*LobStoryVoteReq) ProtoMessage()    {}
func (*LobStoryVoteReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc3d4fb1c88266a9, []int{11}
}

func (m *LobStoryVoteReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LobStoryVoteReq.Unmarshal(m, b)
}
func (m *LobStoryVoteReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LobStoryVoteReq.Marshal(b, m, deterministic)
}
func (m *LobStoryVoteReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LobStoryVoteReq.Merge(m, src)
}
func (m *LobStoryVoteReq) XXX_Size() int {
	return xxx_messageInfo_LobStoryVoteReq.Size(m)
}
func (m *LobStoryVoteReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LobStoryVoteReq.DiscardUnknown(m)
}

var xxx_messageInfo_LobStoryVoteReq proto.InternalMessageInfo

func (m *LobStoryVoteReq) GetStoryID() int64 {
	if m != nil {
		return m.StoryID
	}
	return 0
}

func (m *LobStoryVoteReq) GetVote() int64 {
	if m != nil {
		return m.Vote
	}
	return 0
}

type LobStoryVoteResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LobStoryVoteResp) Reset()         { *m = LobStoryVoteResp{} }
func (m *LobStoryVoteResp) String() string { return proto.CompactTextString(m) }
func (*LobStoryVoteResp) ProtoMessage()    {}
func (*LobStoryVoteResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc3d4fb1c88266a9, []int{12}
}

func (m *LobStoryVoteResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LobStoryVoteResp.Unmarshal(m, b)
}
func (m *LobStoryVoteResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LobStoryVoteResp.Marshal(b, m, deterministic)
}
func (m *LobStoryVoteResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LobStoryVoteResp.Merge(m, src)
}
func (m *LobStoryVoteResp) XXX_Size() int {
	return xxx_messageInfo_LobStoryVoteResp.Size(m)
}
func (m *LobStoryVoteResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LobStoryVoteResp.DiscardUnknown(m)
}

var xxx_messageInfo_LobStoryVoteResp proto.InternalMessageInfo

type GetWriteLogReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWriteLogReq) Reset()         { *m = GetWriteLogReq{} }
func (m *GetWriteLogReq) String() string { return proto.CompactTextString(m) }
func (*GetWriteLogReq) ProtoMessage()    {}
func (*GetWriteLogReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc3d4fb1c88266a9, []int{13}
}

func (m *GetWriteLogReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWriteLogReq.Unmarshal(m, b)
}
func (m *GetWriteLogReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWriteLogReq.Marshal(b, m, deterministic)
}
func (m *GetWriteLogReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWriteLogReq.Merge(m, src)
}
func (m *GetWriteLogReq) XXX_Size() int {
	return xxx_messageInfo_GetWriteLogReq.Size(m)
}
func (m *GetWriteLogReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWriteLogReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetWriteLogReq proto.InternalMessageInfo

type WriteLogOp struct {
	RowID                string               `protobuf:"bytes,1,opt,name=rowID,proto3" json:"rowID,omitempty"`
	T1                   *timestamp.Timestamp `protobuf:"bytes,2,opt,name=t1,proto3" json:"t1,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *WriteLogOp) Reset()         { *m = WriteLogOp{} }
func (m *WriteLogOp) String() string { return proto.CompactTextString(m) }
func (*WriteLogOp) ProtoMessage()    {}
func (*WriteLogOp) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc3d4fb1c88266a9, []int{14}
}

func (m *WriteLogOp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteLogOp.Unmarshal(m, b)
}
func (m *WriteLogOp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteLogOp.Marshal(b, m, deterministic)
}
func (m *WriteLogOp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteLogOp.Merge(m, src)
}
func (m *WriteLogOp) XXX_Size() int {
	return xxx_messageInfo_WriteLogOp.Size(m)
}
func (m *WriteLogOp) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteLogOp.DiscardUnknown(m)
}

var xxx_messageInfo_WriteLogOp proto.InternalMessageInfo

func (m *WriteLogOp) GetRowID() string {
	if m != nil {
		return m.RowID
	}
	return ""
}

func (m *WriteLogOp) GetT1() *timestamp.Timestamp {
	if m != nil {
		return m.T1
	}
	return nil
}

func init() {
	proto.RegisterEnum("qpuextapi.Payload_PayloadType", Payload_PayloadType_name, Payload_PayloadType_value)
	proto.RegisterType((*QueryReq)(nil), "qpuextapi.QueryReq")
	proto.RegisterType((*QueryResp)(nil), "qpuextapi.QueryResp")
	proto.RegisterType((*QueryResp1)(nil), "qpuextapi.QueryResp1")
	proto.RegisterType((*QueryRespRecord1)(nil), "qpuextapi.QueryRespRecord1")
	proto.RegisterMapType((map[string]*Payload)(nil), "qpuextapi.QueryRespRecord1.ResponseEntry")
	proto.RegisterMapType((map[string]*timestamp.Timestamp)(nil), "qpuextapi.QueryRespRecord1.TimestampEntry")
	proto.RegisterType((*Payload)(nil), "qpuextapi.Payload")
	proto.RegisterType((*QueryRespRecord)(nil), "qpuextapi.QueryRespRecord")
	proto.RegisterMapType((map[string]string)(nil), "qpuextapi.QueryRespRecord.AttributesEntry")
	proto.RegisterMapType((map[string]*timestamp.Timestamp)(nil), "qpuextapi.QueryRespRecord.TimestampEntry")
	proto.RegisterType((*MetricsRequest)(nil), "qpuextapi.MetricsRequest")
	proto.RegisterType((*MetricsResponse)(nil), "qpuextapi.MetricsResponse")
	proto.RegisterType((*Story)(nil), "qpuextapi.Story")
	proto.RegisterType((*LobFrontpageReq)(nil), "qpuextapi.LobFrontpageReq")
	proto.RegisterType((*LobFrontpageResp)(nil), "qpuextapi.LobFrontpageResp")
	proto.RegisterType((*LobStoryVoteReq)(nil), "qpuextapi.LobStoryVoteReq")
	proto.RegisterType((*LobStoryVoteResp)(nil), "qpuextapi.LobStoryVoteResp")
	proto.RegisterType((*GetWriteLogReq)(nil), "qpuextapi.GetWriteLogReq")
	proto.RegisterType((*WriteLogOp)(nil), "qpuextapi.WriteLogOp")
}

func init() { proto.RegisterFile("api/protobuf-spec/qpuextapi.proto", fileDescriptor_dc3d4fb1c88266a9) }

var fileDescriptor_dc3d4fb1c88266a9 = []byte{
	// 1076 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x97, 0xdd, 0x6e, 0xdb, 0x36,
	0x14, 0xc7, 0x63, 0xbb, 0xf9, 0xd0, 0x71, 0x1b, 0xbb, 0x4c, 0xd2, 0xb2, 0xce, 0xd0, 0x65, 0xba,
	0x18, 0xb2, 0x00, 0xf5, 0xd7, 0xa2, 0x61, 0x6c, 0xb1, 0x0d, 0xc9, 0x9a, 0x66, 0x1e, 0xb2, 0xc4,
	0x51, 0x9c, 0xee, 0xe3, 0x66, 0x90, 0x6d, 0xc6, 0x11, 0xea, 0x88, 0x32, 0x49, 0xa7, 0xf3, 0xed,
	0xde, 0x6b, 0xaf, 0xb0, 0x27, 0xd8, 0x0b, 0xec, 0x2d, 0x06, 0x51, 0xb2, 0x2c, 0x3b, 0x64, 0x3a,
	0x60, 0xc0, 0xae, 0x4c, 0x1e, 0xfe, 0x7f, 0x7f, 0x1e, 0xf2, 0x10, 0xa4, 0x05, 0x9f, 0x78, 0xa1,
	0x5f, 0x0b, 0x39, 0x93, 0xac, 0x3b, 0xbe, 0x7a, 0x21, 0x42, 0xda, 0xab, 0x8d, 0xc2, 0x31, 0xfd,
	0x4d, 0x7a, 0xa1, 0x5f, 0x55, 0x71, 0x64, 0xa5, 0x81, 0xca, 0xc7, 0x03, 0xc6, 0x06, 0x43, 0x9a,
	0x02, 0x35, 0xe9, 0xdf, 0x50, 0x21, 0xbd, 0x9b, 0x30, 0xd6, 0xda, 0x9f, 0xc2, 0xda, 0xf9, 0x98,
	0xf2, 0x89, 0x4b, 0x47, 0xa8, 0x02, 0x6b, 0xa3, 0xa8, 0x7d, 0x21, 0x39, 0xce, 0xed, 0xe4, 0x76,
	0x2d, 0x37, 0xed, 0xdb, 0xc7, 0x60, 0x25, 0x3a, 0x11, 0xa2, 0x97, 0x00, 0x9c, 0x8a, 0xd0, 0xa5,
	0x3d, 0xc6, 0xfb, 0x38, 0xb7, 0x53, 0xd8, 0x2d, 0x36, 0x2b, 0xd5, 0x59, 0x1a, 0xa9, 0x32, 0x56,
	0xb8, 0x19, 0xb5, 0xdd, 0x02, 0x48, 0x87, 0x1b, 0xe8, 0x95, 0xc6, 0x69, 0xdb, 0xec, 0xd4, 0x98,
	0xb3, 0xfa, 0x33, 0x0f, 0xe5, 0x45, 0x01, 0x3a, 0x82, 0xb5, 0x48, 0xc2, 0x02, 0x41, 0x13, 0xbf,
	0xcf, 0xee, 0xf1, 0xab, 0xba, 0x89, 0xf6, 0x28, 0x90, 0x7c, 0xe2, 0xa6, 0x28, 0xfa, 0x0e, 0xac,
	0x74, 0xab, 0x70, 0x5e, 0xf9, 0xec, 0xdd, 0xe7, 0xd3, 0x99, 0x8a, 0x63, 0xa3, 0x19, 0x5c, 0x39,
	0x83, 0x47, 0x73, 0x93, 0xa0, 0x32, 0x14, 0xde, 0xd1, 0x49, 0xb2, 0xc3, 0x51, 0x13, 0xed, 0xc2,
	0xf2, 0xad, 0x37, 0x1c, 0x53, 0x9c, 0xdf, 0xc9, 0xed, 0x16, 0x9b, 0x28, 0x33, 0x51, 0xdb, 0x9b,
	0x0c, 0x99, 0xd7, 0x77, 0x63, 0xc1, 0xcb, 0xfc, 0x97, 0xb9, 0xca, 0x4f, 0xb0, 0x3e, 0x3f, 0x9b,
	0xc6, 0xb1, 0x3e, 0xef, 0x58, 0xa9, 0xc6, 0xe7, 0xa0, 0x3a, 0x3d, 0x07, 0xb3, 0x7c, 0x33, 0xce,
	0xf6, 0xef, 0x39, 0x58, 0x4d, 0x26, 0x44, 0x4d, 0x78, 0x20, 0x27, 0x21, 0x55, 0xa6, 0xeb, 0xcd,
	0xe7, 0x77, 0x53, 0x9a, 0xfe, 0x76, 0x26, 0x21, 0x75, 0x95, 0x16, 0x6d, 0x66, 0x67, 0x7d, 0x98,
	0x38, 0xdb, 0x2f, 0xa0, 0x98, 0x91, 0x22, 0x80, 0x95, 0x8b, 0x8e, 0xdb, 0x3a, 0x3d, 0x2e, 0x2f,
	0xa1, 0x55, 0x28, 0xb4, 0x4e, 0x3b, 0xe5, 0x1c, 0xb2, 0x60, 0xf9, 0xcd, 0xc9, 0xd9, 0x41, 0xa7,
	0x9c, 0xb7, 0xff, 0xca, 0x43, 0x69, 0x61, 0x7b, 0xd1, 0x36, 0x58, 0x5c, 0xb5, 0x7e, 0xf5, 0xfb,
	0xd3, 0xa3, 0x19, 0x07, 0x5a, 0x7d, 0xf4, 0x3d, 0x80, 0x27, 0x25, 0xf7, 0xbb, 0x63, 0x49, 0xc5,
	0x87, 0x6b, 0x55, 0x3d, 0x48, 0xc5, 0x71, 0xad, 0x32, 0x34, 0x3a, 0xce, 0x96, 0xbd, 0xf0, 0xa1,
	0xe3, 0x73, 0x4f, 0xd5, 0xbf, 0x82, 0xd2, 0xc2, 0x3c, 0x9a, 0x2a, 0xcd, 0xed, 0x97, 0xf5, 0xff,
	0xd4, 0xb8, 0x0c, 0xeb, 0x3f, 0x50, 0xc9, 0xfd, 0x9e, 0x70, 0xe9, 0x68, 0x4c, 0x85, 0xb4, 0xff,
	0xb6, 0xa0, 0x94, 0x86, 0x92, 0xe3, 0xff, 0x05, 0x3c, 0x09, 0x98, 0xf4, 0xaf, 0xfc, 0x9e, 0x27,
	0x7d, 0x16, 0x9c, 0x78, 0x92, 0x06, 0xbd, 0x49, 0xdb, 0xa9, 0xab, 0x04, 0x72, 0xae, 0x61, 0xd4,
	0xc4, 0x91, 0xba, 0x4a, 0xd2, 0xc0, 0x11, 0x33, 0xe7, 0xe0, 0xc2, 0x3d, 0x9c, 0x63, 0xe4, 0x08,
	0x7e, 0x70, 0x0f, 0x47, 0x50, 0x13, 0x36, 0x43, 0xce, 0x7a, 0x54, 0x08, 0x3f, 0x18, 0x64, 0x56,
	0xb7, 0xac, 0x28, 0xed, 0x98, 0x9e, 0x21, 0x75, 0xbc, 0x62, 0x62, 0x88, 0x89, 0x71, 0xf0, 0xaa,
	0x91, 0x71, 0x0c, 0x0c, 0xc1, 0x6b, 0x46, 0x86, 0xa0, 0x3a, 0x6c, 0x5c, 0x71, 0x2a, 0xae, 0x03,
	0x2a, 0x44, 0x66, 0x39, 0x96, 0x42, 0x74, 0x43, 0x5a, 0x82, 0xd4, 0x31, 0x18, 0x08, 0x62, 0x20,
	0x1c, 0x5c, 0x34, 0x11, 0x8e, 0x9e, 0x20, 0xf8, 0xa1, 0x89, 0x20, 0xa8, 0x0a, 0x28, 0x0d, 0xbf,
	0xa5, 0x5c, 0xf8, 0x2c, 0x10, 0x75, 0xfc, 0x48, 0x01, 0x9a, 0x11, 0xad, 0xbe, 0x81, 0xd7, 0x0d,
	0xfa, 0x86, 0x56, 0xdf, 0xc4, 0x25, 0x83, 0xbe, 0xa9, 0xd5, 0xef, 0xe3, 0xb2, 0x41, 0xbf, 0x8f,
	0xf6, 0x61, 0x4b, 0x48, 0x4f, 0xd2, 0xcb, 0xb0, 0xef, 0x49, 0x9a, 0xa9, 0xc4, 0x63, 0x85, 0xe8,
	0x07, 0x0d, 0x14, 0xa9, 0x63, 0x64, 0xa4, 0x88, 0x91, 0x72, 0xf0, 0x86, 0x99, 0x72, 0x4c, 0x14,
	0xc1, 0x9b, 0x66, 0x8a, 0xa0, 0xe7, 0x00, 0xef, 0x0e, 0x27, 0x92, 0x8a, 0x0b, 0x1a, 0x48, 0xbc,
	0xa5, 0xa4, 0x99, 0x08, 0xda, 0x85, 0xd2, 0xf4, 0xe9, 0x8c, 0x6e, 0x9d, 0x68, 0xc5, 0x4f, 0x94,
	0x68, 0x31, 0x7c, 0x47, 0x49, 0xea, 0xf8, 0xa9, 0x46, 0x49, 0x34, 0x4a, 0x07, 0x63, 0x9d, 0xd2,
	0xb9, 0xab, 0x24, 0xf8, 0x99, 0x4e, 0x49, 0xec, 0xf7, 0xb0, 0x7c, 0x21, 0x19, 0x57, 0x57, 0xaf,
	0xf4, 0xe5, 0x90, 0x26, 0x17, 0x6a, 0xdc, 0x41, 0x3b, 0x50, 0xec, 0x53, 0xd1, 0xe3, 0x7e, 0x18,
	0xdd, 0x17, 0xc9, 0xb5, 0x9c, 0x0d, 0x21, 0x0c, 0xab, 0xe2, 0x9a, 0x71, 0xd9, 0x7a, 0xad, 0x6e,
	0x26, 0xcb, 0x9d, 0x76, 0xd1, 0x47, 0x60, 0xdd, 0x32, 0x49, 0xbf, 0x65, 0xe3, 0x40, 0xaa, 0xdb,
	0xa7, 0xe0, 0xce, 0x02, 0xf6, 0x63, 0x28, 0x9d, 0xb0, 0xee, 0x1b, 0xce, 0x02, 0x19, 0x7a, 0x03,
	0xea, 0xd2, 0x91, 0xfd, 0x35, 0x94, 0xe7, 0x43, 0x22, 0x44, 0x7b, 0xb0, 0x2a, 0x24, 0xe3, 0x3e,
	0x15, 0xc9, 0x9f, 0x97, 0x72, 0xe6, 0xf5, 0x51, 0x99, 0xbb, 0x53, 0x81, 0xfd, 0x8d, 0xb2, 0x54,
	0xc1, 0xb7, 0x4c, 0x46, 0x96, 0x2a, 0xbb, 0xa8, 0xdf, 0x7a, 0xad, 0xd6, 0x55, 0x70, 0xa7, 0x5d,
	0x84, 0xe0, 0x41, 0x94, 0x8c, 0x5a, 0x52, 0xc1, 0x55, 0x6d, 0x1b, 0xa9, 0x04, 0x32, 0x06, 0x22,
	0x8c, 0x9e, 0x87, 0x63, 0x2a, 0x7f, 0xe4, 0xbe, 0xa4, 0x27, 0x6c, 0x10, 0xa5, 0x79, 0x0a, 0x30,
	0xed, 0x9e, 0x85, 0xd1, 0xbe, 0x71, 0xf6, 0x3e, 0xf1, 0xb7, 0xdc, 0xb8, 0x83, 0xf6, 0x20, 0x2f,
	0x1b, 0xff, 0xe2, 0x1d, 0xca, 0xcb, 0x46, 0xf3, 0x8f, 0x02, 0xac, 0x9c, 0xb7, 0x2f, 0x0f, 0xda,
	0x2d, 0x44, 0x92, 0xff, 0x82, 0x97, 0x81, 0xc7, 0x27, 0x68, 0xe3, 0xee, 0x43, 0x3b, 0xaa, 0x6c,
	0xea, 0x5e, 0x5f, 0x7b, 0x09, 0xbd, 0x82, 0xe2, 0x0c, 0x6d, 0xe8, 0xd9, 0x2d, 0x1d, 0xdb, 0xb0,
	0x97, 0xd0, 0x11, 0xc0, 0x31, 0x95, 0xc9, 0x9b, 0x87, 0x9e, 0x65, 0x64, 0xf3, 0x4f, 0x63, 0xa5,
	0xa2, 0x1b, 0x8a, 0x4f, 0x94, 0xbd, 0x84, 0x4e, 0xe1, 0xf1, 0x09, 0xeb, 0x0a, 0x49, 0xb9, 0x48,
	0xab, 0x88, 0xb2, 0xc8, 0x42, 0xc5, 0x2b, 0xdb, 0xc6, 0x31, 0xb5, 0xa6, 0x8c, 0x5f, 0x5a, 0x94,
	0x45, 0xbf, 0x6c, 0xb9, 0x17, 0xfd, 0xe6, 0x2b, 0xb9, 0x84, 0x3a, 0xf0, 0xf4, 0x8e, 0x5f, 0x2b,
	0x10, 0x94, 0xcb, 0xff, 0xe0, 0x7a, 0xf8, 0x33, 0x6c, 0xf9, 0xac, 0x3a, 0xe0, 0x61, 0x4f, 0x55,
	0x98, 0x8e, 0x45, 0x6f, 0xe8, 0xd3, 0x40, 0x1e, 0xae, 0x9d, 0xb7, 0x2f, 0xdb, 0x51, 0xcd, 0xdb,
	0xb9, 0x5f, 0xf6, 0x07, 0xbe, 0xbc, 0x1e, 0x77, 0xab, 0x3d, 0x76, 0x53, 0xeb, 0xdf, 0x7a, 0xc2,
	0x1f, 0x7a, 0xa2, 0x96, 0xc8, 0x6b, 0x7e, 0x20, 0x29, 0x0f, 0xbc, 0x61, 0xfc, 0x55, 0x32, 0xfb,
	0x7c, 0xe9, 0xae, 0xa8, 0xc0, 0xe7, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x9a, 0xd3, 0x93, 0x75,
	0xe4, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QPUAPIClient is the client API for QPUAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QPUAPIClient interface {
	QueryUnary(ctx context.Context, in *QueryReq, opts ...grpc.CallOption) (*QueryResp, error)
	QueryUnary1(ctx context.Context, in *QueryReq, opts ...grpc.CallOption) (*QueryResp1, error)
	GetMetrics(ctx context.Context, in *MetricsRequest, opts ...grpc.CallOption) (*MetricsResponse, error)
	LobstersFrontpage(ctx context.Context, in *LobFrontpageReq, opts ...grpc.CallOption) (*LobFrontpageResp, error)
	LobstersStoryVote(ctx context.Context, in *LobStoryVoteReq, opts ...grpc.CallOption) (*LobStoryVoteResp, error)
	LobstersStoryVoteInsert(ctx context.Context, in *LobStoryVoteReq, opts ...grpc.CallOption) (*LobStoryVoteResp, error)
}

type qPUAPIClient struct {
	cc *grpc.ClientConn
}

func NewQPUAPIClient(cc *grpc.ClientConn) QPUAPIClient {
	return &qPUAPIClient{cc}
}

func (c *qPUAPIClient) QueryUnary(ctx context.Context, in *QueryReq, opts ...grpc.CallOption) (*QueryResp, error) {
	out := new(QueryResp)
	err := c.cc.Invoke(ctx, "/qpuextapi.QPUAPI/QueryUnary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qPUAPIClient) QueryUnary1(ctx context.Context, in *QueryReq, opts ...grpc.CallOption) (*QueryResp1, error) {
	out := new(QueryResp1)
	err := c.cc.Invoke(ctx, "/qpuextapi.QPUAPI/QueryUnary1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qPUAPIClient) GetMetrics(ctx context.Context, in *MetricsRequest, opts ...grpc.CallOption) (*MetricsResponse, error) {
	out := new(MetricsResponse)
	err := c.cc.Invoke(ctx, "/qpuextapi.QPUAPI/GetMetrics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qPUAPIClient) LobstersFrontpage(ctx context.Context, in *LobFrontpageReq, opts ...grpc.CallOption) (*LobFrontpageResp, error) {
	out := new(LobFrontpageResp)
	err := c.cc.Invoke(ctx, "/qpuextapi.QPUAPI/LobstersFrontpage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qPUAPIClient) LobstersStoryVote(ctx context.Context, in *LobStoryVoteReq, opts ...grpc.CallOption) (*LobStoryVoteResp, error) {
	out := new(LobStoryVoteResp)
	err := c.cc.Invoke(ctx, "/qpuextapi.QPUAPI/LobstersStoryVote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qPUAPIClient) LobstersStoryVoteInsert(ctx context.Context, in *LobStoryVoteReq, opts ...grpc.CallOption) (*LobStoryVoteResp, error) {
	out := new(LobStoryVoteResp)
	err := c.cc.Invoke(ctx, "/qpuextapi.QPUAPI/LobstersStoryVoteInsert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QPUAPIServer is the server API for QPUAPI service.
type QPUAPIServer interface {
	QueryUnary(context.Context, *QueryReq) (*QueryResp, error)
	QueryUnary1(context.Context, *QueryReq) (*QueryResp1, error)
	GetMetrics(context.Context, *MetricsRequest) (*MetricsResponse, error)
	LobstersFrontpage(context.Context, *LobFrontpageReq) (*LobFrontpageResp, error)
	LobstersStoryVote(context.Context, *LobStoryVoteReq) (*LobStoryVoteResp, error)
	LobstersStoryVoteInsert(context.Context, *LobStoryVoteReq) (*LobStoryVoteResp, error)
}

func RegisterQPUAPIServer(s *grpc.Server, srv QPUAPIServer) {
	s.RegisterService(&_QPUAPI_serviceDesc, srv)
}

func _QPUAPI_QueryUnary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QPUAPIServer).QueryUnary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qpuextapi.QPUAPI/QueryUnary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QPUAPIServer).QueryUnary(ctx, req.(*QueryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _QPUAPI_QueryUnary1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QPUAPIServer).QueryUnary1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qpuextapi.QPUAPI/QueryUnary1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QPUAPIServer).QueryUnary1(ctx, req.(*QueryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _QPUAPI_GetMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QPUAPIServer).GetMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qpuextapi.QPUAPI/GetMetrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QPUAPIServer).GetMetrics(ctx, req.(*MetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QPUAPI_LobstersFrontpage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LobFrontpageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QPUAPIServer).LobstersFrontpage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qpuextapi.QPUAPI/LobstersFrontpage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QPUAPIServer).LobstersFrontpage(ctx, req.(*LobFrontpageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _QPUAPI_LobstersStoryVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LobStoryVoteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QPUAPIServer).LobstersStoryVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qpuextapi.QPUAPI/LobstersStoryVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QPUAPIServer).LobstersStoryVote(ctx, req.(*LobStoryVoteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _QPUAPI_LobstersStoryVoteInsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LobStoryVoteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QPUAPIServer).LobstersStoryVoteInsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qpuextapi.QPUAPI/LobstersStoryVoteInsert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QPUAPIServer).LobstersStoryVoteInsert(ctx, req.(*LobStoryVoteReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _QPUAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "qpuextapi.QPUAPI",
	HandlerType: (*QPUAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryUnary",
			Handler:    _QPUAPI_QueryUnary_Handler,
		},
		{
			MethodName: "QueryUnary1",
			Handler:    _QPUAPI_QueryUnary1_Handler,
		},
		{
			MethodName: "GetMetrics",
			Handler:    _QPUAPI_GetMetrics_Handler,
		},
		{
			MethodName: "LobstersFrontpage",
			Handler:    _QPUAPI_LobstersFrontpage_Handler,
		},
		{
			MethodName: "LobstersStoryVote",
			Handler:    _QPUAPI_LobstersStoryVote_Handler,
		},
		{
			MethodName: "LobstersStoryVoteInsert",
			Handler:    _QPUAPI_LobstersStoryVoteInsert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/protobuf-spec/qpuextapi.proto",
}
